In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("mw_govjob_listings_scraped.csv")

In [3]:
df

,Job Title,Company Name,Company Location,Salary,Description,Link,Job Category
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia","Starting at $87,198 (GS 12)",Help\r\n \n...,https://www.usajobs.gov/GetJob/ViewDetails/622...,Data Analyst
1,IT Specialist (DATAMGT) (Data and Reporting An...,Department of the Treasury,No location provided,"Starting at $92,143 (GS 13)",Help\r\n \n...,https://www.usajobs.gov/GetJob/ViewDetails/621...,Data Analyst
2,Program Analyst (Data Science),Department of Veterans Affairs,No location provided,"Starting at $66,829 (GS 12)",Help\r\n \n...,https://www.usajobs.gov/GetJob/ViewDetails/620...,Data Analyst
3,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts","Starting at $59,498 (GS 9-11)",Help\r\n \n...,https://www.usajobs.gov/GetJob/ViewDetails/622...,Data Analyst
4,Interdisciplinary (Data Research Analyst),Other Agencies and Independent Organizations,"Alexandria, Virginia","Starting at $103,690 (AD 03)",Help\r\n \n...,https://www.usajobs.gov/GetJob/ViewDetails/623...,Data Analyst
...,...,...,...,...,...,...,...
11282,Research Economist Research Mathematicia...,Department of the Treasury,"Washington, District of Columbia","Starting at $158,184 (OR 70)",Help\r\n \n...,https://www.usajobs.gov/GetJob/ViewDetails/619...,Statistician
11283,Physical Scientist/Biologist/Mathematical Stat...,Department of the Interior,No location provided,"Starting at $53,433 (GS 9)",Help\r\n \n...,https://www.usajobs.gov/GetJob/ViewDetails/621...,Statistician
11284,Physical Scientist/Biologist/Mathematical Stat...,Department of the Interior,No location provided,"Starting at $77,488 (GS 12)",Help\r\n \n...,https://www.usajobs.gov/GetJob/ViewDetails/621...,Statistician
11285,Health Statistician - PD21E022 - Center for Qu...,Department of Health And Human Services,"Rockville, Maryland","Starting at $103,690 (GS 13)",Help\r\n \n...,https://www.usajobs.gov/GetJob/ViewDetails/620...,Statistician
11286,"Mathematical Statistician (Education), GS-1529...",Department of Education,"Washington, District of Columbia","Starting at $144,128 (GS 15)",Help\r\n \n...,https://www.usajobs.gov/GetJob/ViewDetails/621...,Statistician

In [4]:
df = df.drop('Description', axis=1)
df = df.drop('Link', axis=1)

In [5]:
df.drop(df.loc[df['Salary']==''].index, inplace=True)

In [6]:
df['Salary'] = df['Salary'].str.replace('Starting at','')

In [8]:
df['Salary'] =df['Salary'] .str[:8]

In [10]:
df['Salary'] = df['Salary'].str.replace('$','')
df['Salary'] = df['Salary'].str.replace('NF','')
df['Salary'] = df['Salary'].str.replace('(','')
df['Salary'] = df['Salary'].str.replace(',','')
df['Salary'] = df['Salary'].str.replace('0 GS','')
df['Salary'] = df['Salary'].str.replace('0 HS','')

In [12]:
df.dtypes

Job Title           object
Company Name        object
Company Location    object
Salary              object
Job Category        object
dtype: object

In [13]:
df['Salary'] = df['Salary'].replace(np.nan, 0)

In [15]:
df['Salary'] = df['Salary'].str.strip()

In [16]:
df['Salary'] = df['Salary'].fillna('')

In [17]:
df['Salary'] = df['Salary'].str.strip()

In [18]:
# df["Salary"] = df['Salary'].str.replace(' ', '').astype(float)

In [19]:
df['Salary'] = pd.to_numeric(df['Salary'], downcast='float')

In [20]:
df['Salary'] = df['Salary'].apply(lambda x: x*2000 if x<100 else x)

In [21]:
df

,Job Title,Company Name,Company Location,Salary,Job Category
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Data Analyst
1,IT Specialist (DATAMGT) (Data and Reporting An...,Department of the Treasury,No location provided,92143.0,Data Analyst
2,Program Analyst (Data Science),Department of Veterans Affairs,No location provided,66829.0,Data Analyst
3,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Data Analyst
4,Interdisciplinary (Data Research Analyst),Other Agencies and Independent Organizations,"Alexandria, Virginia",10369.0,Data Analyst
...,...,...,...,...,...
11282,Research Economist Research Mathematicia...,Department of the Treasury,"Washington, District of Columbia",15818.0,Statistician
11283,Physical Scientist/Biologist/Mathematical Stat...,Department of the Interior,No location provided,53433.0,Statistician
11284,Physical Scientist/Biologist/Mathematical Stat...,Department of the Interior,No location provided,77488.0,Statistician
11285,Health Statistician - PD21E022 - Center for Qu...,Department of Health And Human Services,"Rockville, Maryland",10369.0,Statistician
11286,"Mathematical Statistician (Education), GS-1529...",Department of Education,"Washington, District of Columbia",14412.0,Statistician

In [22]:
df['Company Location'].unique().tolist()

['Washington, District of Columbia',
 'No location provided',
 'West Roxbury, Massachusetts',
 'Alexandria, Virginia',
 'Indianapolis, Indiana',
 'Woodlawn, Maryland',
 'Gallup, New Mexico',
 'Quantico, Virginia',
 'Phoenix, Arizona',
 'Andrews AFB, Maryland',
 'Whitehall, Ohio',
 'Fort Meade, Maryland',
 'Montgomery, Alabama',
 'Washington DC, District of Columbia',
 'Arlington, Virginia',
 'Bethesda, Maryland',
 'District of Columbia, District of Columbia',
 'Key West, Florida',
 'Baton Rouge, Louisiana',
 'Wright-Patterson AFB, Ohio',
 'Greenbelt, Maryland',
 'Air Force Academy, Colorado',
 'Fort Sam Houston, Texas',
 'Fort Huachuca, Arizona',
 'Naval Air Station Jacksonville, Florida',
 'Norfolk, Virginia',
 'Germantown, Maryland',
 'Riyadh, Saudi Arabia',
 'Walla Walla, Washington',
 'Hanscom AFB, Massachusetts',
 'Otis ANG Base, Massachusetts',
 'Silver Spring, Maryland',
 'College Park, Maryland',
 'Cleveland, Ohio',
 'Redstone Arsenal, Alabama',
 'North Chicago, Illinois',
 'Lincoln, Nebraska',
 'Lakewood, Colorado',
 'Latham, New York',
 'Houston, Texas',
 'Westhampton Beach, New York',
 'Savannah, Georgia',
 'Columbia, South Carolina',
 'Augusta, Maine',
 'Portland, Oregon',
 'Coatesville, Pennsylvania',
 'Port Alsworth, Alaska',
 'Fort Gordon, Georgia',
 'Fort Polk, Louisiana',
 'Dallas, Texas',
 'Dayton, Ohio',
 'Pentagon, Arlington, Virginia',
 'Grafenwohr, Germany',
 'Austin, Texas',
 'Fort Belvoir, Virginia',
 'Fort Detrick, Maryland',
 'Fort Campbell, Kentucky',
 'Fort Eustis, Virginia',
 'Langley AFB, Virginia',
 'San Diego, California',
 'Seattle, Washington',
 'Boulder City, Nevada',
 'Scott AFB, Illinois',
 'Rock Island, Illinois',
 'Camp Shelby, Mississippi',
 'Fort Irwin, California',
 'Stuttgart, Germany',
 'Waco, Texas',
 'Columbus, Ohio',
 'Fort McCoy, Wisconsin',
 'Kuwait, Kuwait',
 'New Orleans, Louisiana',
 'Buckley AFB, Colorado',
 'Baileys Crossroads, Virginia',
 'Denver, Colorado',
 'Smyrna, Tennessee',
 'Warren, Michigan',
 'Pittsburgh, Pennsylvania',
 'Cincinnati, Ohio',
 'Los Angeles, California',
 'Charleston, South Carolina',
 'Martinez, California',
 'San Francisco, California',
 'Fort Worth, Texas',
 'Gainesville, Florida',
 'Kirtland AFB, New Mexico',
 'Chicago, Illinois',
 'Lakehurst, New Jersey',
 'Anchorage, Alaska',
 'North Charleston, South Carolina',
 'New York, New York',
 'Patuxent River, Maryland',
 'Washington Navy Yard, District of Columbia',
 'Hines, Illinois',
 'Marietta, Georgia',
 'Omaha, Nebraska',
 'Texarkana, Texas',
 'Vicksburg, Mississippi',
 'Asheville, North Carolina',
 'Richmond, Virginia',
 'Saint Louis, Missouri',
 'Wiesbaden, Germany',
 'Barksdale AFB, Louisiana',
 'Vienna, Austria',
 'Minneapolis, Minnesota',
 'Wichita, Kansas',
 'Ann Arbor, Michigan',
 'Suffolk, Virginia',
 'Tinker AFB, Oklahoma',
 'Hickam AFB, Hawaii',
 'Springfield, Virginia',
 'Offutt AFB, Nebraska',
 'Montgomery County, Maryland',
 'Battle Creek, Michigan',
 'Jackson, Mississippi',
 'Manama, Bahrain',
 'Glynco, Georgia',
 'Detroit, Michigan',
 'McGuire AFB, New Jersey',
 'Annapolis Junction, Maryland',
 'Mare Island Naval Shipyard, California',
 'Magna, Utah',
 'Togus, Maine',
 'Oak Ridge, Tennessee',
 'Robins AFB, Georgia',
 'Leavenworth, Kansas',
 'Camp Murray, Washington',
 'Letterkenny Army Depot, Pennsylvania',
 'Madison, Wisconsin',
 'Great Falls, Montana',
 'Greensboro, North Carolina',
 'Fort Lee, Virginia',
 'Albuquerque, New Mexico',
 'Polacca, Arizona',
 'Fort Riley, Kansas',
 'Orlando, Florida',
 'Peach Springs, Arizona',
 'San Antonio, Texas',
 'Kaiserslautern, Germany',
 'Natick, Massachusetts',
 'Bangor, Maine',
 'Reston, Virginia',
 'Johnson City, Tennessee',
 'Naval Base, Norfolk, Virginia',
 'Naval Support Activity, Mechanicsburg, Pennsylvania',
 'Fort Collins, Colorado',
 'Vicenza, Italy',
 'Fort Knox, Kentucky',
 'Fort McNair, District of Columbia',
 'Fort Bragg, North Carolina',
 'Lackland AFB, Texas',
 'Tripler Army Medical Center, Hawaii',
 'Millington, Tennessee',
 'Kansas City, Missouri',
 'Point Mugu, California',
 'James Island, South Carolina',
 'Muskogee, Oklahoma',
 'Fairchild AFB, Washington',
 'Joint Base Lewis-McChord, Washington',
 'Monterey, California',
 'Bangor, Washington',
 'Atlanta, Georgia',
 'Carson City, Nevada',
 'Mobile, Alabama',
 'New Cumberland Defense Logistics Center, Pennsylvania',
 'Hill AFB, Utah',
 'Aberdeen Proving Ground, Maryland',
 'Springfield, Illinois',
 'Fort Sill, Oklahoma',
 'Lansing, Michigan',
 'Oklahoma City, Oklahoma',
 'Camp Lejeune, North Carolina',
 'Nashville, Tennessee',
 'Fort Bliss, Texas',
 'Fort Jackson, South Carolina',
 'Pearl Harbor, Hawaii',
 'Peoria, Illinois',
 'Loma Linda, California',
 'Jefferson City, Missouri',
 'Philadelphia, Pennsylvania',
 'Klamath Falls, Oregon',
 'Colorado Springs, Colorado',
 'Terre Haute, Indiana',
 'Fort Rucker, Alabama',
 'Memphis, Tennessee',
 'Palo Alto, California',
 'Joint Base McGuire-Dix-Lakehurst, New Jersey',
 'Bremerton, Washington',
 'Fort Leavenworth, Kansas',
 'Amarillo, Texas',
 'Bay Pines, Florida',
 'White Sands Missile Range, New Mexico',
 'Sioux Falls, South Dakota',
 'Miami, Florida',
 'Point Loma Complex, San Diego, California',
 'Fort Leonard Wood, Missouri',
 'Fort Meade Naval Facilities, Maryland',
 'Shaw AFB, South Carolina',
 'Belle Chasse, Louisiana',
 'Flowood, Mississippi',
 'Selfridge ANG Base, Michigan',
 'Garmisch, Germany',
 'Capodichino, Italy',
 'Albany Marine Corps Logistics Base, Georgia',
 'Twentynine Palms, California',
 'Fresno, California',
 'Camp Foster, Japan',
 'Meridian, Mississippi',
 'Naval Air Station Pensacola , Florida',
 'Great Lakes, Illinois',
 'Duluth, Georgia',
 'Ogden, Utah',
 'China Lake, California',
 'Camp Pendleton, California',
 'Kue, Japan',
 'Des Moines, Washington',
 'Yokosuka Naval Base, Japan',
 'Camp Douglas, Wisconsin',
 'Naval Shipyard, Portsmouth, Virginia',
 'Pittsfield, Massachusetts',
 'Falls Church, Virginia',
 'Joint Base Anacostia-Bolling, District of Columbia',
 'Rockville, Maryland',
 'Flagstaff, Arizona',
 'Akron, Ohio',
 'Prescott, Arizona',
 'Salisbury, North Carolina',
 'Cheyenne, Wyoming',
 'Camp Beauregard, Louisiana',
 'Fairfax, Virginia',
 'Newington, New Hampshire',
 'Little Creek Amphibious Base, Virginia',
 'Chandler, Arizona',
 'Suitland, Maryland',
 'Elizabeth City, North Carolina',
 'Baltimore, Maryland',
 'Tuscaloosa, Alabama',
 'Chester, Virginia',
 'Huntsville, Alabama',
 'Jacksonville, Florida',
 'Salt Lake City, Utah',
 'Coronado, California',
 'Glendale, Colorado',
 'McAlester, Oklahoma',
 'College Park, Georgia',
 'Cambridge, Massachusetts',
 'Greenville, South Carolina',
 'Hanover, Maryland',
 'Lexington, Kentucky',
 'Downers Grove, Illinois',
 'Crane, Indiana',
 'Dahlgren, Virginia',
 'Port Hueneme, California',
 'Keyport, Washington',
 'Spawar, Charleston, South Carolina',
 'Indian Head, Maryland',
 'Saint Inigoes, Maryland',
 'Lafayette, Louisiana',
 'Anniston Army Depot, Alabama',
 'Aviano, Italy',
 'Charleston AFB, South Carolina',
 'Charleston, West Virginia',
 'Minot AFB, North Dakota',
 'Huntington, West Virginia',
 'Wilmington, North Carolina',
 'Lufkin, Texas',
 'Laughlin AFB, Texas',
 'Buffalo, New York',
 'Parsippany, New Jersey',
 'Bemidji, Minnesota',
 'Sacramento, California',
 'Des Moines, Iowa',
 'Edwards AFB, California',
 'Fort Harrison, Montana',
 'Pleasant Valley, Iowa',
 'Butler, Pennsylvania',
 'Fargo, North Dakota',
 'Picatinny Arsenal, New Jersey',
 'Concord, Massachusetts',
 'Fort Hood, Texas',
 'Hawthorne, Nevada',
 'Pearl Harbor Naval Base, Oahu, Hawaii',
 'Kings Bay, Georgia',
 'National Maritime Intelligence Center, Maryland',
 'Jefferson Barracks, Missouri',
 'Lisle, Illinois',
 'Cherry Point, North Carolina',
 'Boston, Massachusetts',
 'Yokosuka, Japan',
 'Poplar Bluff, Missouri',
 'Kings, New York',
 'Sunnyvale, California',
 'Sandy, Utah',
 'Virginia Beach, Virginia',
 'Seymour Johnson AFB, North Carolina',
 'Naval Base Newport, Rhode Island',
 'Eglin AFB, Florida',
 'Coolidge, Arizona',
 'Grand Forks AFB, North Dakota',
 'Mather AFB, California',
 'Providence, Rhode Island',
 'Naval Station Complex, San Diego, California',
 'Little Rock AFB, Arkansas',
 'Long Beach, California',
 'Atlantic City, New Jersey',
 'Boulder, Colorado',
 'Huron, South Dakota',
 'Tulsa, Oklahoma',
 'Murfreesboro, Tennessee',
 'Annapolis, Maryland',
 'Vancouver, Washington',
 'Olmsted, Illinois',
 'Eagle Butte, South Dakota',
 'Big Spring, Texas',
 'Pawnee, Oklahoma',
 'Yakima, Washington',
 'Rhinelander, Wisconsin',
 'Camp Arifjan, Kuwait',
 'Clay Center, Nebraska',
 'Holloman AFB, New Mexico',
 'Guantanamo Bay, Cuba',
 'Landstuhl, Germany',
 'Louisville, Kentucky',
 'Fort Stewart, Georgia',
 'Mayport, Florida',
 'Kadena Air Base Okinawa, Japan',
 'Zama, Camp Zama, Japan',
 'El Paso, Texas',
 'Saint Paul, Minnesota',
 'Naval Air Station Jacksonville , Florida',
 'Leavenworth, Washington',
 'Chattanooga, Tennessee',
 'Naval Business Center, Philadelphia, Pennsylvania',
 'Mechanicsburg, Pennsylvania',
 'Farmington, New Mexico',
 'Belle Vernon, Pennsylvania',
 'Decatur, Alabama',
 'Holton, Kansas',
 'Massena, New York',
 'Elmendorf AFB, Alaska',
 'York, Pennsylvania',
 'Red Lake, Minnesota',
 'Reno, Nevada',
 'Camp Perry, Ohio',
 'Beltsville, Maryland',
 'Dulce, New Mexico',
 'Naval Air Station San Diego, California',
 'Harrisburg, Illinois',
 'Garden City, New York',
 'Bradford, Pennsylvania',
 'PYONG TAEK, South Korea',
 'Hampton, Virginia',
 'Kane County, Utah',
 'Page, Arizona',
 'Tacoma, Washington',
 'Kaneohe, Hawaii',
 'Fort Thompson, South Dakota',
 'Parker, Arizona',
 'Mills, Wyoming',
 'Hilo, Hawaii',
 'Billings, Montana',
 'Ashburn, Virginia',
 'Dickinson, North Dakota',
 'Pawhuska, Oklahoma',
 'Everett, Washington',
 'Rota, Spain',
 'Davis Monthan AFB, Arizona',
 'Goodfellow AFB, Texas',
 'Morrisville, North Carolina',
 'Champaign, Illinois',
 'Naval Facilities Engineering Command, Atlantic, Virginia',
 'Iwakuni, Japan',
 'Stennis Space Center, Mississippi',
 'Tuba City, Arizona',
 'Camp Humphreys, South Korea',
 'Finegayan, Guam',
 'Sheppard AFB, Texas',
 'New London, Connecticut',
 'El Segundo, California',
 'West Point, New York',
 'Portsmouth, Virginia',
 'Sigonella Sicily, Italy',
 'Honolulu, Hawaii',
 'Naval Air Station Whidbey Island, Washington',
 'Iowa City, Iowa',
 'Wyndmoor, Pennsylvania',
 'Jordan, Jordan',
 'Naval Medical Center, San Diego, California',
 'Okinawa Island, Japan',
 'Corpus Christi, Texas',
 'Parlier, California',
 'Tucson, Arizona',
 'Monterey County, California',
 'Gulfport, Mississippi',
 'Concord, California',
 'Poston, Arizona',
 'Ventura, California',
 'Biloxi, Mississippi',
 'Golden Pond, Kentucky',
 'Corvallis, Oregon',
 'Lenexa, Kansas',
 'Barstow, California',
 'Stafford, Virginia',
 'Santa Cruz, California',
 'Sterling, Virginia',
 'Nigeria, Nigeria',
 'Fort Carson, Colorado',
 'Toppenish, Washington',
 'Nespelem, Washington',
 'Jacksonville Naval Hospital, Florida',
 'Crownpoint, New Mexico',
 'Moffett Field, California',
 'Luke AFB, Arizona',
 'Pine Ridge, South Dakota',
 'Lawrence, Kansas',
 'Adelphi, Maryland',
 'Alton, Illinois',
 'Butner Federal Correctional Complex, North Carolina',
 'Durham, North Carolina',
 'Willows, California',
 'Vernal, Utah',
 'Yuma, Arizona',
 'Randolph AFB, Texas',
 'Winchester, Virginia',
 'Milwaukee, Wisconsin',
 'Natchitoches, Louisiana',
 'Wallops Island, Virginia',
 'Beaumont, Texas',
 'Tomah, Wisconsin',
 'Hawaii National Park, Hawaii',
 'Fort Hunter Liggett, California',
 'Carlisle Barracks, Pennsylvania',
 'Hanoi, Vietnam',
 'Kelly AFB, Texas',
 'Devils Tower, Wyoming',
 'Dugway Proving Ground, Utah',
 'San Juan, Puerto Rico',
 'Dunn Loring, Virginia',
 'North Highlands, California',
 'Springfield, Ohio',
 'Linthicum Heights, Maryland',
 'Fort Shafter, Hawaii',
 'Camp Springs, Maryland',
 'Martinsburg, West Virginia',
 'Newark, New Jersey',
 'Manchester, New Hampshire',
 'Charlottesville, Virginia',
 'Danville, Illinois',
 'Fort Smith, Arkansas',
 'Princeton, Oregon',
 'Wheeler Army Airfield, Hawaii',
 'Lorton, Virginia',
 'Syracuse, New York',
 'Kennedy Space Center, Florida',
 'Mesa, Arizona',
 'Bahrain Island, Bahrain',
 'Aberdeen, Maryland',
 'Garden Grove, California',
 'Tobyhanna, Pennsylvania',
 'Arlington Heights, Illinois',
 'Fort Snelling, Minnesota',
 'Geary County, Kansas',
 'Boise, Idaho',
 'Fort Drum, New York',
 'Darien, Illinois',
 'Saint Cloud, Minnesota',
 'Zutendaal, Belgium',
 'Saint Augustine, Florida',
 'Normal, Illinois',
 'Westfield, Massachusetts',
 'Camp Henry, South Korea',
 'Aiea, Hawaii',
 'Panama City, Florida',
 'Eygelshoven, Netherlands',
 'Herlong Sierra Ordnance Depot, California',
 'Naval Support Activity, Mechanicsburg Detach., Philadelphia, Pennsylvania',
 'Fairbanks, Alaska',
 'Umatilla, Oregon',
 'Camp J T Robinson, Arkansas',
 'Salina, Kansas',
 'Carderock Springs, Maryland',
 'Scotia, New York',
 'Bismarck, North Dakota',
 'Florence, Arizona',
 'Frederick, Maryland',
 'Sequoia National Park, California',
 'Altus AFB, Oklahoma',
 'Orlando Naval Warfare Center, Florida',
 'Vandenberg AFB, California',
 'Warren AFB, Wyoming',
 'Lawton, Oklahoma',
 'Ashland, Kentucky',
 'MacDill AFB, Florida',
 'Pueblo, Colorado',
 'Rickenbacker AFB, Ohio',
 'Eielson AFB, Alaska',
 'Kunsan, South Korea',
 'Fayetteville, Arkansas',
 'Sioux City, Iowa',
 'Mansfield, Ohio',
 'Longmont, Colorado',
 'Fort Wayne, Indiana',
 'Lihue, Hawaii',
 'Whiteman AFB, Missouri',
 'Stewart AFB, New York',
 'Riverdale, Maryland',
 'Garden City, Georgia',
 'Kingsley Field, Oregon',
 'Rancho Cordova, California',
 'West Jordan, Utah',
 'Williamstown, West Virginia',
 'North Kingstown, Rhode Island',
 'Hilliard, Florida',
 'Weldon Spring, Missouri',
 'Kailua Kona, Hawaii',
 'Fort Benning, Georgia',
 'Auburn, Washington',
 'Gardner, Kansas',
 'Tallahassee, Florida',
 'Westbury, New York',
 'Marion, Illinois',
 'Littleton, Colorado',
 'Fort Devens, Massachusetts',
 'Adams County, Pennsylvania',
 'Peterson AFB, Colorado',
 'Saint Joseph, Missouri',
 'Bronx, New York',
 'East Orange, New Jersey',
 'Rochester, New York',
 'Merrimack, New Hampshire',
 'Coraopolis, Pennsylvania',
 'Portland, Maine',
 'Concord, New Hampshire',
 'Lubbock, Texas',
 'Midland, Texas',
 'White River Junction, Vermont',
 'Gregg Township, Pennsylvania',
 'Bennettsville, South Carolina',
 'Chinhae, South Korea',
 'Mountain Home AFB, Idaho',
 'Hurlburt Field, Florida',
 'McConnell AFB, Kansas',
 'Watertown, South Dakota',
 'Beaufort, South Carolina',
 'Marine Corps Air Station Miramar, California',
 'Pollock, Louisiana',
 'Seagoville, Texas',
 'Lompoc, California',
 'Florence, Colorado',
 'Edgefield, South Carolina',
 'Miami-Dade County, Florida',
 'Panama City Naval Surface Warfare Center, Florida',
 'Ventura County, California',
 'Bishop, California',
 'Coleman, Florida',
 'Los Alamos, New Mexico',
 'Augusta, Georgia',
 'Destrehan, Louisiana',
 'Galveston, Texas',
 'Panama City, Panama',
 'Crow Agency, Montana',
 'Bath, New York',
 'Las Vegas, Nevada',
 'Colts Neck, New Jersey',
 'Shiprock, New Mexico',
 'Fort Campbell, Tennessee',
 'Homestead AFB, Florida',
 'Oceanside, California',
 'Goose Creek, South Carolina',
 'Winnemucca, Nevada',
 'Ajo, Arizona',
 'Fort Ben Harrison, Indiana',
 'Ringwood, Illinois',
 'Misawa AFB, Japan',
 'Cannon AFB, New Mexico',
 'Leeds, Massachusetts',
 'Temple, Texas',
 'Chambersburg, Pennsylvania',
 'Eugene, Oregon',
 'Schofield Barracks, Hawaii',
 'Middletown, Rhode Island',
 'Grand Junction, Colorado',
 'La Grande, Oregon',
 'Wahiawa, Hawaii',
 'Fredericksburg, Virginia',
 'Groton Submarine Base, Connecticut',
 'Fairview, Oregon',
 'Hillsboro, Oregon',
 'Columbus, Georgia',
 'Juneau, Alaska',
 'Middletown, Ohio',
 'Little Rock, Arkansas',
 'Albany, New York',
 'Southampton, New York',
 'Lockport, New York',
 'Tuskegee, Alabama',
 'Camp Blanding, Florida',
 'Sasebo Naval Base, Japan',
 'Tyndall AFB, Florida',
 'Jay, Oklahoma',
 'Appleton, Wisconsin',
 'Greenville, North Carolina',
 'Morehead City, North Carolina',
 'Butte, Montana',
 'Chillicothe, Ohio',
 'Spokane, Washington',
 'West Palm Beach, Florida',
 'Lyons, New Jersey',
 'Tongduchon, South Korea',
 'Prince George, Virginia',
 'Gladstone, Michigan',
 'Burlington, Vermont',
 'Jacksonville, North Carolina',
 'Dublin, Georgia',
 'Fayetteville, North Carolina',
 'Wilkes Barre, Pennsylvania',
 'Green Bay, Wisconsin',
 'Ramstein, Germany',
 'Manila, Philippines',
 'Albany, Georgia',
 'Sarajevo, Bosnia and Herzegovina',
 'Beaver, West Virginia',
 'Jonesville, Virginia',
 'Lebanon, Pennsylvania',
 'Three Rivers, Texas',
 'Dublin, California',
 'Santa Rosa, California',
 'Manchester, Kentucky',
 'Anderson, South Carolina',
 'Schriever AFB, Colorado',
 'Port Charlotte, Florida',
 'Harrisburg, Pennsylvania',
 'Viera, Florida',
 'La Crosse, Wisconsin',
 'Forrest City, Arkansas',
 'North Little Rock, Arkansas',
 'Clarksburg, West Virginia',
 'Kodiak, Alaska',
 'Salem, Virginia',
 'Tampa, Florida',
 'Fort Thomas, Kentucky',
 'Denali Park, Alaska',
 'Grand Canyon, Arizona',
 'Irving, Texas',
 'White City, Oregon',
 'White Earth, Minnesota',
 'Marshall, Texas',
 'Kahului, Hawaii',
 'Pasadena, California',
 'Duluth, Minnesota',
 'Bothell, Washington',
 'Las Cruces, New Mexico',
 'Niagara Falls, New York',
 'Maynard, Massachusetts',
 'Raleigh, North Carolina',
 'Camp Mabry, Texas',
 'Souda Bay, Greece',
 'Ford Island, Hawaii',
 'Loveland, Colorado',
 'Centennial, Colorado',
 'Red River Army Depot, Texas',
 'Canon City, Colorado',
 'Grand Coulee, Washington',
 'Van Nuys, California',
 'Nellis AFB, Nevada',
 'South Burlington, Vermont',
 'Naval Air Station Oceana, Virginia',
 'Clinton, Oklahoma',
 'Portales, New Mexico',
 'Thief River Falls, Minnesota',
 'West Haven, Connecticut',
 'Corona, California',
 'Lake City, Florida',
 'Herndon, Virginia',
 'Charleston County, South Carolina',
 'Gaithersburg, Maryland',
 'Parris Island, South Carolina',
 'Kearneysville, West Virginia',
 'Lanham-Seabrook, Maryland',
 'Rosslyn, Virginia',
 'Fort Duchesne, Utah',
 'Sasebo, Japan',
 'Qatar, Qatar',
 'Fort Greely, Alaska',
 'Maxwell AFB, Alabama',
 'Brunssum, Netherlands',
 'Brussels, Belgium',
 'Fort Hamilton, New York',
 'Salem, Oregon',
 'Naval Medical Center, Portsmouth, Virginia',
 'Brook Park, Ohio',
 'Naval Surface Warfare Center, Maryland']

In [23]:
# df['Company Location'] = df['Company Location'].str.strip()

In [24]:
df_company_location = df.join(df['Company Location'].str.split(',', 1, expand=True).rename(columns={0:'city', 1:'State'}))

In [25]:
df_company_location

,Job Title,Company Name,Company Location,Salary,Job Category,city,State
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Data Analyst,Washington,District of Columbia
1,IT Specialist (DATAMGT) (Data and Reporting An...,Department of the Treasury,No location provided,92143.0,Data Analyst,No location provided,None
2,Program Analyst (Data Science),Department of Veterans Affairs,No location provided,66829.0,Data Analyst,No location provided,None
3,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Data Analyst,West Roxbury,Massachusetts
4,Interdisciplinary (Data Research Analyst),Other Agencies and Independent Organizations,"Alexandria, Virginia",10369.0,Data Analyst,Alexandria,Virginia
...,...,...,...,...,...,...,...
11282,Research Economist Research Mathematicia...,Department of the Treasury,"Washington, District of Columbia",15818.0,Statistician,Washington,District of Columbia
11283,Physical Scientist/Biologist/Mathematical Stat...,Department of the Interior,No location provided,53433.0,Statistician,No location provided,None
11284,Physical Scientist/Biologist/Mathematical Stat...,Department of the Interior,No location provided,77488.0,Statistician,No location provided,None
11285,Health Statistician - PD21E022 - Center for Qu...,Department of Health And Human Services,"Rockville, Maryland",10369.0,Statistician,Rockville,Maryland
11286,"Mathematical Statistician (Education), GS-1529...",Department of Education,"Washington, District of Columbia",14412.0,Statistician,Washington,District of Columbia

In [26]:
df_company_location= df_company_location.drop(df_company_location.loc[df_company_location['State']==' Saudi Arabia'].index, inplace=True)

In [ ]:
df_company_location.drop(df_company_location.loc[df_company_location['State']=='Philippines'].index, inplace=True)

In [ ]:
df_company_location.drop(df_company_location.loc[df_company_location['State']=='Qatar'].index, inplace=False)

In [ ]:
df_company_location.drop(df_company_location.loc[df_company_location['State']=='Greece'].index, inplace=True)

In [ ]:
df_company_location

In [ ]:
df_company_location=df_company_location.drop(df_company_location.loc[df_company_location['State']==' Qatar'].index, inplace=False)

In [ ]:
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Bahrain'].index, inplace=True)

In [ ]:
df_company_location['State'].unique().tolist()

In [ ]:


df_company_location=df_company_location.drop(df_company_location.loc[df_company_location['State']==' Greece'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Bahrain'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Camp Zama, Japan'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Netherlands'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Philippines'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Jordan'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Bosnia and Herzegovina'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Nigeria'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Italy'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Belgium'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Japan'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Kuwait'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Vietnam'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Germany'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Austria'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Cuba'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==' Spain'].index, inplace=True)
df_company_location.drop(df_company_location.loc[df_company_location['State']==''].index, inplace=True)
df_company_location['State'] = df_company_location['State'].str.replace('Oahu, ','')
df_company_location['State'] = df_company_location['State'].str.replace('Mechanicsburg, ','')
df_company_location['State'] = df_company_location['State'].str.replace('Philadelphia, ','')
df_company_location['State'] = df_company_location['State'].str.replace('Atlantic, ','')
df_company_location['State'] = df_company_location['State'].str.replace('Charleston, ','')
df_company_location['State'] = df_company_location['State'].str.replace('San Diego, ','')
df_company_location['State'] = df_company_location['State'].str.replace('Mechanicsburg Detach., ','')
df_company_location['State'] = df_company_location['State'].str.replace('Mechanicsburg Detach., ','')
df_company_location['State'] = df_company_location['State'].str.replace('Portsmouth, ','')
df_company_location['State'] = df_company_location['State'].str.replace('Portsmouth, ','')
df_company_location['State'] = df_company_location['State'].str.replace('Norfolk, Virginia','')
df_company_location['State'] = df_company_location['State'].str.replace('Arlington, ','')
df_company_location['State'] = df_company_location['State'].str.replace("''",'')
df_company_location["State"] =df_company_location["State"].str.strip()

In [ ]:
df_company_location['State'].unique().tolist()

In [ ]:
df_company_location['State'].nunique()

In [ ]:
df_company_location

In [ ]:
df_company_location = df_company_location.drop('Company Location', axis=1)

In [ ]:
df_company_location.to_csv("cpj_govjobs_cleaned4.csv", index=False)