In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../Resources/Govjobs_cleaned_with_description.csv')

In [3]:
df

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Analyst,Washington,District of Columbia
1,IT Specialist (DATAMGT) (Data and Reporting An...,Department of the Treasury,No location provided,92143.0,Help\r\n \n...,Data Analyst,No location provided,NaN
2,Program Analyst (Data Science),Department of Veterans Affairs,No location provided,66829.0,Help\r\n \n...,Data Analyst,No location provided,NaN
3,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Data Analyst,West Roxbury,Massachusetts
4,Interdisciplinary (Data Research Analyst),Other Agencies and Independent Organizations,"Alexandria, Virginia",10369.0,Help\r\n \n...,Data Analyst,Alexandria,Virginia
...,...,...,...,...,...,...,...,...
10999,Research Economist Research Mathematicia...,Department of the Treasury,"Washington, District of Columbia",15818.0,Help\r\n \n...,Statistician,Washington,District of Columbia
11000,Physical Scientist/Biologist/Mathematical Stat...,Department of the Interior,No location provided,53433.0,Help\r\n \n...,Statistician,No location provided,NaN
11001,Physical Scientist/Biologist/Mathematical Stat...,Department of the Interior,No location provided,77488.0,Help\r\n \n...,Statistician,No location provided,NaN
11002,Health Statistician - PD21E022 - Center for Qu...,Department of Health And Human Services,"Rockville, Maryland",10369.0,Help\r\n \n...,Statistician,Rockville,Maryland
11003,"Mathematical Statistician (Education), GS-1529...",Department of Education,"Washington, District of Columbia",14412.0,Help\r\n \n...,Statistician,Washington,District of Columbia

In [4]:
df['Data Analyst'] = (df["Job Title"].str.lower()
                            .str.contains("data analyst", regex=False, na=False)
                            .astype(int))
Data_Analyst_df = df.loc[df['Data Analyst'] == 1]
Data_Analyst_df["Category"] = "Data Analyst"
del Data_Analyst_df["Data Analyst"]
Data_Analyst_df

<ipython-input-4-84dd14c6f739>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data_Analyst_df["Category"] = "Data Analyst"

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State,Category
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Analyst,Washington,District of Columbia,Data Analyst
3,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Data Analyst,West Roxbury,Massachusetts,Data Analyst
11,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Analyst,Gallup,New Mexico,Data Analyst
12,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Analyst,Gallup,New Mexico,Data Analyst
837,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Engineer,Washington,District of Columbia,Data Analyst
868,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Data Engineer,West Roxbury,Massachusetts,Data Analyst
882,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Engineer,Gallup,New Mexico,Data Analyst
883,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Engineer,Gallup,New Mexico,Data Analyst
1620,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Scientist,Washington,District of Columbia,Data Analyst
1684,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Data Scientist,West Roxbury,Massachusetts,Data Analyst
1735,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Scientist,Gallup,New Mexico,Data Analyst
1736,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Scientist,Gallup,New Mexico,Data Analyst
1849,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Architect,Washington,District of Columbia,Data Analyst
1904,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Data Architect,West Roxbury,Massachusetts,Data Analyst
1925,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Architect,Gallup,New Mexico,Data Analyst
1926,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Architect,Gallup,New Mexico,Data Analyst
1960,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Big Data Software Engineer,Washington,District of Columbia,Data Analyst
1997,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Big Data Software Engineer,West Roxbury,Massachusetts,Data Analyst
2011,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Big Data Software Engineer,Gallup,New Mexico,Data Analyst
2012,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Big Data Software Engineer,Gallup,New Mexico,Data Analyst
3594,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Business Intelligence Analyst,Washington,District of Columbia,Data Analyst
4245,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Business Intelligence Analyst,West Roxbury,Massachusetts,Data Analyst
4309,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Business Intelligence Analyst,Gallup,New Mexico,Data Analyst
4310,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Business Intelligence Analyst,Gallup,New Mexico,Data Analyst
4476,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Logistics Analyst,Washington,District of Columbia,Data Analyst
5131,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Logistics Analyst,West Roxbury,Massachusetts,Data Analyst
5196,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Logistics Analyst,Gallup,New Mexico,Data Analyst
5197,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Logistics Analyst,Gallup,New Mexico,Data Analyst
5469,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Business Systems Analyst,Washington,District of Columbia,Data Analyst
6230,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Business Systems Analyst,West Roxbury,Massachusetts,Data Analyst
6297,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Business Systems Analyst,Gallup,New Mexico,Data Analyst
6298,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Business Systems Analyst,Gallup,New Mexico,Data Analyst
6380,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Marketing Analyst,Washington,District of Columbia,Data Analyst
7031,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Marketing Analyst,West Roxbury,Massachusetts,Data Analyst
7096,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Marketing Analyst,Gallup,New Mexico,Data Analyst
7097,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Marketing Analyst,Gallup,New Mexico,Data Analyst
7171,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Warehouse Manager,Washington,District of Columbia,Data Analyst
7210,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Data Warehouse Manager,West Roxbury,Massachusetts,Data Analyst
7224,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Warehouse Manager,Gallup,New Mexico,Data Analyst
7225,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Warehouse Manager,Gallup,New Mexico,Data Analyst
8465,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Modeler,Washington,District of Columbia,Data Analyst
8496,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Data Modeler,West Roxbury,Massachusetts,Data Analyst
8510,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Modeler,Gallup,New Mexico,Data Analyst
8511,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Modeler,Gallup,New Mexico,Data Analyst
8530,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Quantitative Analyst,Washington,District of Columbia,Data Analyst
9181,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Quantitative Analyst,West Roxbury,Massachusetts,Data Analyst
9246,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Quantitative Analyst,Gallup,New Mexico,Data Analyst
9247,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Quantitative Analyst,Gallup,New Mexico,Data Analyst
9889,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,IT Systems Analyst,Washington,District of Columbia,Data Analyst
10761,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,IT Systems Analyst,West Roxbury,Massachusetts,Data Analyst
10879,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,IT Systems Analyst,Gallup,New Mexico,Data Analyst
10880,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,IT Systems Analyst,Gallup,New Mexico,Data Analyst

In [5]:
df['Computer Scientist'] = df["Job Title"].str.contains("Computer Scientist", case=False, na=False).astype(int)
Computer_Scientist_df = df.loc[df['Computer Scientist'] == 1]
Computer_Scientist_df["Category"] = "Computer Scientist"
del Computer_Scientist_df['Data Analyst']
del Computer_Scientist_df["Computer Scientist"]

<ipython-input-5-282d3e244201>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Computer_Scientist_df["Category"] = "Computer Scientist"

In [6]:
Computer_Scientist_df

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State,Category
835,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,Data Analyst,Patuxent River,Maryland,Computer Scientist
1070,"Computer Engineer, Computer Scientist, Electri...",Other Agencies and Independent Organizations,"Rockville, Maryland",12253.0,Help\r\n \n...,Data Engineer,Rockville,Maryland,Computer Scientist
1289,COMPUTER SCIENTIST/ENGINEER,Department of the Air Force,"Eglin AFB, Florida",77488.0,Help\r\n \n...,Data Engineer,Eglin AFB,Florida,Computer Scientist
1366,INTERDISCIPLINARY COMPUTER SCIENTIST/COMPUTER ...,Department of the Air Force,"Hanscom AFB, Massachusetts",10260.0,Help\r\n \n...,Data Engineer,Hanscom AFB,Massachusetts,Computer Scientist
1536,Interdisciplinary Computer Engineer / Computer...,Legislative Branch,"Washington, District of Columbia",10840.0,Help\r\n \n...,Data Engineer,Washington,District of Columbia,Computer Scientist
1607,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,Data Engineer,Patuxent River,Maryland,Computer Scientist
1659,Computer Scientist,Department of the Air Force,No location provided,66829.0,Help\r\n \n...,Data Scientist,No location provided,NaN,Computer Scientist
1662,COMPUTER SCIENTIST,Department of the Navy,"Saint Inigoes, Maryland",87198.0,Help\r\n \n...,Data Scientist,Saint Inigoes,Maryland,Computer Scientist
1663,Computer Scientist,Department of the Air Force,No location provided,50106.0,Help\r\n \n...,Data Scientist,No location provided,NaN,Computer Scientist
1665,Computer Scientist,Department of the Air Force,No location provided,30414.0,Help\r\n \n...,Data Scientist,No location provided,NaN,Computer Scientist
1667,Computer Scientist,Department of the Treasury,No location provided,11097.0,Help\r\n \n...,Data Scientist,No location provided,NaN,Computer Scientist
1668,COMPUTER SCIENTIST,Department of the Navy,"Stafford, Virginia",87198.0,Help\r\n \n...,Data Scientist,Stafford,Virginia,Computer Scientist
1673,COMPUTER SCIENTIST,Department of the Army,"Picatinny Arsenal, New Jersey",10647.0,Help\r\n \n...,Data Scientist,Picatinny Arsenal,New Jersey,Computer Scientist
1675,COMPUTER SCIENTIST,Department of the Air Force,"Eglin AFB, Florida",10888.0,Help\r\n \n...,Data Scientist,Eglin AFB,Florida,Computer Scientist
1702,COMPUTER SCIENTIST/ENGINEER,Department of the Air Force,"Eglin AFB, Florida",77488.0,Help\r\n \n...,Data Scientist,Eglin AFB,Florida,Computer Scientist
1785,Student Trainee (Computer Scientist) (PATHWAYS),Department of Commerce,"Boulder, Colorado",25093.0,Help\r\n \n...,Data Scientist,Boulder,Colorado,Computer Scientist
1794,"Computer Scientist, GS-1550-07/09/11/12, Censu...",Department of Commerce,"Suitland, Maryland",49157.0,Help\r\n \n...,Data Scientist,Suitland,Maryland,Computer Scientist
1795,"Computer Scientist, GS-1550-07/09/11/12, Censu...",Department of Commerce,"Suitland, Maryland",49157.0,Help\r\n \n...,Data Scientist,Suitland,Maryland,Computer Scientist
1805,Interdisciplinary Computer Engineer / Computer...,Legislative Branch,"Washington, District of Columbia",10840.0,Help\r\n \n...,Data Scientist,Washington,District of Columbia,Computer Scientist
1809,Public Notice for Computer Scientist Cybersecu...,Department of Transportation,No location provided,66829.0,Help\r\n \n...,Data Scientist,No location provided,NaN,Computer Scientist
1810,Public Notice for Computer Scientist Cybersecu...,Department of Transportation,No location provided,56205.0,Help\r\n \n...,Data Scientist,No location provided,NaN,Computer Scientist
1821,"Computer Scientist, AST, Computer Research and...",National Aeronautics and Space Administration,"Cleveland, Ohio",80743.0,Help\r\n \n...,Data Scientist,Cleveland,Ohio,Computer Scientist
1829,INTERDISCIPLINARY COMPUTER SCIENTIST/COMPUTER ...,Department of the Air Force,"Hanscom AFB, Massachusetts",10260.0,Help\r\n \n...,Data Scientist,Hanscom AFB,Massachusetts,Computer Scientist
1832,"Computer Engineer, Computer Scientist, Electri...",Other Agencies and Independent Organizations,"Rockville, Maryland",12253.0,Help\r\n \n...,Data Scientist,Rockville,Maryland,Computer Scientist
1835,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,Data Scientist,Patuxent River,Maryland,Computer Scientist
2199,"Computer Engineer, Computer Scientist, Electri...",Other Agencies and Independent Organizations,"Rockville, Maryland",12253.0,Help\r\n \n...,Big Data Software Engineer,Rockville,Maryland,Computer Scientist
2418,COMPUTER SCIENTIST/ENGINEER,Department of the Air Force,"Eglin AFB, Florida",77488.0,Help\r\n \n...,Big Data Software Engineer,Eglin AFB,Florida,Computer Scientist
2495,INTERDISCIPLINARY COMPUTER SCIENTIST/COMPUTER ...,Department of the Air Force,"Hanscom AFB, Massachusetts",10260.0,Help\r\n \n...,Big Data Software Engineer,Hanscom AFB,Massachusetts,Computer Scientist
2663,Interdisciplinary Computer Engineer / Computer...,Legislative Branch,"Washington, District of Columbia",10840.0,Help\r\n \n...,Big Data Software Engineer,Washington,District of Columbia,Computer Scientist
2734,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,Big Data Software Engineer,Patuxent River,Maryland,Computer Scientist
2931,"Computer Engineer, Computer Scientist, Electri...",Other Agencies and Independent Organizations,"Rockville, Maryland",12253.0,Help\r\n \n...,Machine Learning Engineer,Rockville,Maryland,Computer Scientist
3147,COMPUTER SCIENTIST/ENGINEER,Department of the Air Force,"Eglin AFB, Florida",77488.0,Help\r\n \n...,Machine Learning Engineer,Eglin AFB,Florida,Computer Scientist
3224,INTERDISCIPLINARY COMPUTER SCIENTIST/COMPUTER ...,Department of the Air Force,"Hanscom AFB, Massachusetts",10260.0,Help\r\n \n...,Machine Learning Engineer,Hanscom AFB,Massachusetts,Computer Scientist
3394,Interdisciplinary Computer Engineer / Computer...,Legislative Branch,"Washington, District of Columbia",10840.0,Help\r\n \n...,Machine Learning Engineer,Washington,District of Columbia,Computer Scientist
3465,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,Machine Learning Engineer,Patuxent River,Maryland,Computer Scientist
4375,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,Business Intelligence Analyst,Patuxent River,Maryland,Computer Scientist
5266,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,Logistics Analyst,Patuxent River,Maryland,Computer Scientist
6363,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,Business Systems Analyst,Patuxent River,Maryland,Computer Scientist
7166,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,Marketing Analyst,Patuxent River,Maryland,Computer Scientist
9315,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,Quantitative Analyst,Patuxent River,Maryland,Computer Scientist
10966,"INTERDISCIPLINARY COMPUTER SCIENTIST, GENERAL ...",Department of the Navy,"Patuxent River, Maryland",87198.0,Help\r\n \n...,IT Systems Analyst,Patuxent River,Maryland,Computer Scientist

In [7]:
df['IT Specialist'] = (df["Job Title"].str.lower()
                            .str.contains("it specialist", regex=False, na=False)
                            .astype(int))
it_specialist_df = df.loc[df['IT Specialist'] == 1]
it_specialist_df["Category"] = "IT Specialist"
del it_specialist_df['Data Analyst']
del it_specialist_df["Computer Scientist"]
del it_specialist_df["IT Specialist"]

<ipython-input-7-7ccbb0de860e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  it_specialist_df["Category"] = "IT Specialist"

In [8]:
it_specialist_df

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State,Category
1,IT Specialist (DATAMGT) (Data and Reporting An...,Department of the Treasury,No location provided,92143.0,Help\r\n \n...,Data Analyst,No location provided,NaN,IT Specialist
17,IT Specialist (DATAMGT),Department of Veterans Affairs,No location provided,46083.0,Help\r\n \n...,Data Analyst,No location provided,NaN,IT Specialist
18,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961.0,Help\r\n \n...,Data Analyst,Washington,District of Columbia,IT Specialist
19,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961.0,Help\r\n \n...,Data Analyst,Washington,District of Columbia,IT Specialist
20,IT SPECIALIST (DATAMGT) T5,Department of the Army,"Phoenix, Arizona",55355.0,Help\r\n \n...,Data Analyst,Phoenix,Arizona,IT Specialist
...,...,...,...,...,...,...,...,...,...
9795,Supervisor IT Specialist - Cybersecurity (Vali...,Department of the Navy,"Quantico, Virginia",11500.0,Help\r\n \n...,IT Systems Analyst,Quantico,Virginia,IT Specialist
9802,"Senior IT Specialist, (DATAMGT) CG-2210-15 TEM...",Other Agencies and Independent Organizations,"Washington, District of Columbia",12962.0,Help\r\n \n...,IT Systems Analyst,Washington,District of Columbia,IT Specialist
9812,IT Specialist (Policy and Planning/Enterprise ...,Department of the Army,"Pentagon, Arlington, Virginia",12253.0,Help\r\n \n...,IT Systems Analyst,Pentagon,Virginia,IT Specialist
9816,"IT Specialist (Application Software), GS-2210-...",Department of Commerce,"Suitland, Maryland",10369.0,Help\r\n \n...,IT Systems Analyst,Suitland,Maryland,IT Specialist
9817,"Supervisory IT Specialist, CM-2210-01 (Temp Pr...",Other Agencies and Independent Organizations,No location provided,11019.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,IT Specialist

In [9]:
df['Operations Research Analyst'] = (df["Job Title"].str.lower()
                            .str.contains("operations research analyst", regex=False, na=False)
                            .astype(int))
operations_research_analyst_df = df.loc[df['Operations Research Analyst'] == 1]
operations_research_analyst_df["Category"] = "Operations Research Analyst"
del operations_research_analyst_df['Data Analyst']
del operations_research_analyst_df["Computer Scientist"]
del operations_research_analyst_df["IT Specialist"]
del operations_research_analyst_df["Operations Research Analyst"]
operations_research_analyst_df

<ipython-input-9-6f1edc10dd9a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  operations_research_analyst_df["Category"] = "Operations Research Analyst"

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State,Category
15,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755.0,Help\r\n \n...,Data Analyst,No location provided,NaN,Operations Research Analyst
16,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755.0,Help\r\n \n...,Data Analyst,No location provided,NaN,Operations Research Analyst
497,Operations Research Analyst,Department of the Air Force,No location provided,43683.0,Help\r\n \n...,Data Analyst,No location provided,NaN,Operations Research Analyst
499,Operations Research Analyst,Department of the Army,"White Sands Missile Range, New Mexico",77488.0,Help\r\n \n...,Data Analyst,White Sands Missile Range,New Mexico,Operations Research Analyst
500,Operations Research Analyst,Department of Transportation,No location provided,83458.0,Help\r\n \n...,Data Analyst,No location provided,NaN,Operations Research Analyst
...,...,...,...,...,...,...,...,...,...
10907,Operations Research Analyst-Joint Requirements...,Department of Homeland Security,"Washington, District of Columbia",79468.0,Help\r\n \n...,IT Systems Analyst,Washington,District of Columbia,Operations Research Analyst
10928,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Operations Research Analyst
10929,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Operations Research Analyst
10940,General Engineer/Operations Research Analyst (...,Department of Homeland Security,No location provided,81057.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Operations Research Analyst
10941,General Engineer/Operations Research Analyst (...,Department of Homeland Security,No location provided,81057.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Operations Research Analyst

In [10]:
df['Data Engineer'] = (df["Job Title"].str.lower()
                            .str.contains("data engineer", regex=False, na=False)
                            .astype(int))
Data_engineer_df = df.loc[df['Data Engineer'] == 1]
Data_engineer_df["Category"] = "Data Enginner"
del Data_engineer_df['Data Analyst']
del Data_engineer_df["Computer Scientist"]
del Data_engineer_df["IT Specialist"]
del Data_engineer_df["Operations Research Analyst"]
del Data_engineer_df["Data Engineer"]
Data_engineer_df

Empty DataFrame
Columns: [Job Title, Company Name, Company Location, Salary, Description, Job Category, city, State, Category]
Index: []

In [11]:
df['Business Intelligence Specialist'] = (df["Job Title"].str.lower()
                            .str.contains("business intelligence specialist", regex=False, na=False)
                            .astype(int))


Business_intelligence_specialist_df = df.loc[df['Business Intelligence Specialist'] == 1]

Business_intelligence_specialist_df ["Category"] = "Business Intelligence Specialist"
del Business_intelligence_specialist_df ['Data Analyst']
del Business_intelligence_specialist_df ["Computer Scientist"]
del Business_intelligence_specialist_df ["IT Specialist"]
del Business_intelligence_specialist_df ["Operations Research Analyst"]
del Business_intelligence_specialist_df ["Business Intelligence Specialist"]
del Business_intelligence_specialist_df ["Data Engineer"]
Business_intelligence_specialist_df

Empty DataFrame
Columns: [Job Title, Company Name, Company Location, Salary, Description, Job Category, city, State, Category]
Index: []

In [12]:
df['Research Analyst'] = (df["Job Title"].str.lower()
                            .str.contains("research analyst", regex=False, na=False)
                            .astype(int))


Research_analyst_df = df.loc[df['Research Analyst'] == 1]

Research_analyst_df["Category"] = "Research_Analyst"
del Research_analyst_df ['Data Analyst']
del Research_analyst_df ["Computer Scientist"]
del Research_analyst_df ["IT Specialist"]
del Research_analyst_df ["Operations Research Analyst"]
del Research_analyst_df ["Business Intelligence Specialist"]
del Research_analyst_df ["Research Analyst"]
del Research_analyst_df ["Data Engineer"]
Research_analyst_df

<ipython-input-12-579dc7799bc6>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Research_analyst_df["Category"] = "Research_Analyst"

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State,Category
4,Interdisciplinary (Data Research Analyst),Other Agencies and Independent Organizations,"Alexandria, Virginia",10369.0,Help\r\n \n...,Data Analyst,Alexandria,Virginia,Research_Analyst
15,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755.0,Help\r\n \n...,Data Analyst,No location provided,NaN,Research_Analyst
16,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755.0,Help\r\n \n...,Data Analyst,No location provided,NaN,Research_Analyst
497,Operations Research Analyst,Department of the Air Force,No location provided,43683.0,Help\r\n \n...,Data Analyst,No location provided,NaN,Research_Analyst
499,Operations Research Analyst,Department of the Army,"White Sands Missile Range, New Mexico",77488.0,Help\r\n \n...,Data Analyst,White Sands Missile Range,New Mexico,Research_Analyst
...,...,...,...,...,...,...,...,...,...
10907,Operations Research Analyst-Joint Requirements...,Department of Homeland Security,"Washington, District of Columbia",79468.0,Help\r\n \n...,IT Systems Analyst,Washington,District of Columbia,Research_Analyst
10928,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Research_Analyst
10929,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Research_Analyst
10940,General Engineer/Operations Research Analyst (...,Department of Homeland Security,No location provided,81057.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Research_Analyst
10941,General Engineer/Operations Research Analyst (...,Department of Homeland Security,No location provided,81057.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Research_Analyst

In [13]:
df['Chief Data Officer'] = (df["Job Title"].str.lower()
                            .str.contains("cheif data officer", regex=False, na=False)
                            .astype(int))


chief_Data_officer_df = df.loc[df['Chief Data Officer'] == 1]

chief_Data_officer_df["Category"] = "Chief_Data Officer"
del chief_Data_officer_df ['Data Analyst']
del chief_Data_officer_df ["Computer Scientist"]
del chief_Data_officer_df ["IT Specialist"]
del chief_Data_officer_df ["Operations Research Analyst"]
del chief_Data_officer_df ["Business Intelligence Specialist"]
del chief_Data_officer_df ["Research Analyst"]
del chief_Data_officer_df ["Data Engineer"]
del chief_Data_officer_df["Chief Data Officer"]
chief_Data_officer_df

Empty DataFrame
Columns: [Job Title, Company Name, Company Location, Salary, Description, Job Category, city, State, Category]
Index: []

In [14]:
df['Enterprise Data Manager'] = (df["Job Title"].str.lower()
                            .str.contains("enterprise data manager", regex=False, na=False)
                            .astype(int))


Enterprise_Data_manager= df.loc[df['Enterprise Data Manager'] == 1]

Enterprise_Data_manager["Category"] = "Enterprise Data Manager"
del Enterprise_Data_manager['Data Analyst']
del Enterprise_Data_manager["Computer Scientist"]
del Enterprise_Data_manager["IT Specialist"]
del Enterprise_Data_manager["Operations Research Analyst"]
del Enterprise_Data_manager["Business Intelligence Specialist"]
del Enterprise_Data_manager["Research Analyst"]
del Enterprise_Data_manager["Data Engineer"]
del Enterprise_Data_manager["Chief Data Officer"]
del Enterprise_Data_manager["Enterprise Data Manager"]                                 
Enterprise_Data_manager

Empty DataFrame
Columns: [Job Title, Company Name, Company Location, Salary, Description, Job Category, city, State, Category]
Index: []

In [15]:
df['Management and Program Analyst'] = (df["Job Title"].str.lower()
                            .str.contains("management and program analyst", regex=False, na=False)
                            .astype(int))


Management_program_Analyst_df= df.loc[df['Management and Program Analyst'] == 1]

Management_program_Analyst_df["Category"] = "Management program Analyst"
del Management_program_Analyst_df ['Data Analyst']
del Management_program_Analyst_df ["Computer Scientist"]
del Management_program_Analyst_df ["IT Specialist"]
del Management_program_Analyst_df ["Operations Research Analyst"]
del Management_program_Analyst_df ["Business Intelligence Specialist"]
del Management_program_Analyst_df ["Research Analyst"]
del Management_program_Analyst_df ["Data Engineer"]
del Management_program_Analyst_df["Chief Data Officer"]
del Management_program_Analyst_df["Enterprise Data Manager"] 
del Management_program_Analyst_df["Management and Program Analyst"]
Management_program_Analyst_df

<ipython-input-15-56bb16f8f937>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Management_program_Analyst_df["Category"] = "Management program Analyst"

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State,Category
14,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807.0,Help\r\n \n...,Data Analyst,No location provided,NaN,Management program Analyst
413,Management and Program Analyst (Records Manage...,Department of Justice,"Washington, District of Columbia",10369.0,Help\r\n \n...,Data Analyst,Washington,District of Columbia,Management program Analyst
441,Management and Program Analyst (Finance and Bu...,Department of Transportation,"Washington, District of Columbia",73336.0,Help\r\n \n...,Data Analyst,Washington,District of Columbia,Management program Analyst
587,Management and Program Analyst,Department of Homeland Security,No location provided,79468.0,Help\r\n \n...,Data Analyst,No location provided,NaN,Management program Analyst
589,Management and Program Analyst,Department of Homeland Security,"Washington, District of Columbia",10369.0,Help\r\n \n...,Data Analyst,Washington,District of Columbia,Management program Analyst
...,...,...,...,...,...,...,...,...,...
10927,Management and Program Analyst (Organizational...,Legislative Branch,"Washington, District of Columbia",12253.0,Help\r\n \n...,IT Systems Analyst,Washington,District of Columbia,Management program Analyst
10933,Management and Program Analyst (Business Proce...,Department of Agriculture,"Phoenix, Arizona",80275.0,Help\r\n \n...,IT Systems Analyst,Phoenix,Arizona,Management program Analyst
10949,SUPERVISORY MANAGEMENT AND PROGRAM ANALYST (Ch...,Department of Homeland Security,No location provided,93907.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Management program Analyst
10950,Management and Program Analyst (Project Manage...,Department of the Treasury,No location provided,92143.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Management program Analyst
10953,Supervisory Management and Program Analyst (Pr...,Department of the Treasury,No location provided,10999.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Management program Analyst

In [16]:
df['Management and Program Analyst'].value_counts()

0    10372
1      632
Name: Management and Program Analyst, dtype: int64

In [17]:
df['Public Health Analyst'] = (df["Job Title"].str.lower()
                            .str.contains("public health analyst", regex=False, na=False)
                            .astype(int))


public_health_Analyst_df= df.loc[df['Public Health Analyst'] == 1]

public_health_Analyst_df["Category"] = "Public Health Analyst"
del public_health_Analyst_df ['Data Analyst']
del public_health_Analyst_df ["Computer Scientist"]
del public_health_Analyst_df ["IT Specialist"]
del public_health_Analyst_df ["Operations Research Analyst"]
del public_health_Analyst_df ["Business Intelligence Specialist"]
del public_health_Analyst_df ["Research Analyst"]
del public_health_Analyst_df ["Data Engineer"]
del public_health_Analyst_df["Chief Data Officer"]
del public_health_Analyst_df["Enterprise Data Manager"] 
del public_health_Analyst_df["Management and Program Analyst"]
del public_health_Analyst_df["Public Health Analyst"]
public_health_Analyst_df

<ipython-input-17-0e3ae859ff95>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  public_health_Analyst_df["Category"] = "Public Health Analyst"

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State,Category
407,Public Health Analyst,Department of Health And Human Services,"Atlanta, Georgia",97078.0,Help\r\n \n...,Data Analyst,Atlanta,Georgia,Public Health Analyst
409,Public Health Analyst,Department of Health And Human Services,"Atlanta, Georgia",97078.0,Help\r\n \n...,Data Analyst,Atlanta,Georgia,Public Health Analyst
816,Public Health Analyst PD 15R591 / 15R592 - Mat...,Department of Health And Human Services,"Rockville, Maryland",72750.0,Help\r\n \n...,Data Analyst,Rockville,Maryland,Public Health Analyst
817,Public Health Analyst PD 15R591 / 15R592 - Mat...,Department of Health And Human Services,"Rockville, Maryland",72750.0,Help\r\n \n...,Data Analyst,Rockville,Maryland,Public Health Analyst
827,"Supervisory Public Health Analyst - Director, ...",Department of Health And Human Services,"Rockville, Maryland",14412.0,Help\r\n \n...,Data Analyst,Rockville,Maryland,Public Health Analyst
...,...,...,...,...,...,...,...,...,...
10957,"Supervisory Public Health Analyst - Director, ...",Department of Health And Human Services,"Rockville, Maryland",14412.0,Help\r\n \n...,IT Systems Analyst,Rockville,Maryland,Public Health Analyst
10961,Public Health Analyst PD 14R325 / 14R326 - Off...,Department of Health And Human Services,No location provided,46083.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Public Health Analyst
10962,Public Health Analyst PD 14R325 / 14R326 - Off...,Department of Health And Human Services,No location provided,46083.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Public Health Analyst
10963,Public Health Analyst PD 14R327 / 14R329 - Off...,Department of Health And Human Services,No location provided,66829.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Public Health Analyst
10964,Public Health Analyst PD 14R327 / 14R329 - Off...,Department of Health And Human Services,No location provided,66829.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Public Health Analyst

In [18]:
df['Procurement Analyst'] = (df["Job Title"].str.lower()
                            .str.contains("procurement analyst", regex=False, na=False)
                            .astype(int))


Procurement_Analyst_df= df.loc[df['Procurement Analyst'] == 1]

Procurement_Analyst_df["Category"] = "Procurement Analyst"
del Procurement_Analyst_df ['Data Analyst']
del Procurement_Analyst_df ["Computer Scientist"]
del Procurement_Analyst_df ["IT Specialist"]
del Procurement_Analyst_df ["Operations Research Analyst"]
del Procurement_Analyst_df ["Business Intelligence Specialist"]
del Procurement_Analyst_df ["Research Analyst"]
del Procurement_Analyst_df ["Data Engineer"]
del Procurement_Analyst_df["Chief Data Officer"]
del Procurement_Analyst_df["Enterprise Data Manager"] 
del Procurement_Analyst_df["Management and Program Analyst"]
del Procurement_Analyst_df["Public Health Analyst"]
del Procurement_Analyst_df["Procurement Analyst"]
Procurement_Analyst_df

<ipython-input-18-4be8625f17cb>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Procurement_Analyst_df["Category"] = "Procurement Analyst"

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State,Category
392,Procurement Analyst,Department of the Army,"Mobile, Alabama",92143.0,Help\r\n \n...,Data Analyst,Mobile,Alabama,Procurement Analyst
393,Procurement Analyst,Department of Defense,"New Cumberland Defense Logistics Center, Penns...",10369.0,Help\r\n \n...,Data Analyst,New Cumberland Defense Logistics Center,Pennsylvania,Procurement Analyst
394,Procurement Analyst,General Services Administration,"Lakewood, Colorado",10102.0,Help\r\n \n...,Data Analyst,Lakewood,Colorado,Procurement Analyst
395,PROCUREMENT ANALYST,Department of the Air Force,"Hill AFB, Utah",92143.0,Help\r\n \n...,Data Analyst,Hill AFB,Utah,Procurement Analyst
396,Procurement Analyst,Department of the Air Force,"Scott AFB, Illinois",78624.0,Help\r\n \n...,Data Analyst,Scott AFB,Illinois,Procurement Analyst
...,...,...,...,...,...,...,...,...,...
10786,Procurement Analyst (Public Notice Flyer),Department of Homeland Security,"Washington, District of Columbia",10369.0,Help\r\n \n...,IT Systems Analyst,Washington,District of Columbia,Procurement Analyst
10890,Contract Specialist/Procurement Analyst - Dire...,Department of Transportation,"Cambridge, Massachusetts",82721.0,Help\r\n \n...,IT Systems Analyst,Cambridge,Massachusetts,Procurement Analyst
10891,Contract Specialist/Procurement Analyst (Direc...,Department of Transportation,No location provided,64009.0,You will serve as a Contract Specialist and ma...,IT Systems Analyst,No location provided,NaN,Procurement Analyst
10892,Contract Specialist/Procurement Analyst (Direc...,Department of Transportation,No location provided,10780.0,You will serve as a Contract Specialist and ma...,IT Systems Analyst,No location provided,NaN,Procurement Analyst
10952,"Contract Spec/Administrator/Negotiator, Procur...",General Services Administration,No location provided,64649.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Procurement Analyst

In [19]:
df['Health Insurance Analyst'] = (df["Job Title"].str.lower()
                            .str.contains("health insurance analyst", regex=False, na=False)
                            .astype(int))


health_insurance_Analyst_df= df.loc[df['Health Insurance Analyst'] == 1]

health_insurance_Analyst_df["Category"] = "Health Insurance Analyst"
del health_insurance_Analyst_df ['Data Analyst']
del health_insurance_Analyst_df ["Computer Scientist"]
del health_insurance_Analyst_df ["IT Specialist"]
del health_insurance_Analyst_df ["Operations Research Analyst"]
del health_insurance_Analyst_df ["Business Intelligence Specialist"]
del health_insurance_Analyst_df ["Research Analyst"]
del health_insurance_Analyst_df ["Data Engineer"]
del health_insurance_Analyst_df["Chief Data Officer"]
del health_insurance_Analyst_df["Enterprise Data Manager"] 
del health_insurance_Analyst_df["Management and Program Analyst"]
del health_insurance_Analyst_df["Public Health Analyst"]
del health_insurance_Analyst_df["Procurement Analyst"]
del health_insurance_Analyst_df["Health Insurance Analyst"]
health_insurance_Analyst_df

Empty DataFrame
Columns: [Job Title, Company Name, Company Location, Salary, Description, Job Category, city, State, Category]
Index: []

In [20]:
df['Social Science Analyst'] = (df["Job Title"].str.lower()
                            .str.contains("social science analyst", regex=False, na=False)
                            .astype(int))


Social_Science_Analyst_df= df.loc[df['Social Science Analyst'] == 1]

Social_Science_Analyst_df["Category"] = "Social Science Analyst"
del Social_Science_Analyst_df ['Data Analyst']
del Social_Science_Analyst_df ["Computer Scientist"]
del Social_Science_Analyst_df ["IT Specialist"]
del Social_Science_Analyst_df ["Operations Research Analyst"]
del Social_Science_Analyst_df ["Business Intelligence Specialist"]
del Social_Science_Analyst_df ["Research Analyst"]
del Social_Science_Analyst_df ["Data Engineer"]
del Social_Science_Analyst_df["Chief Data Officer"]
del Social_Science_Analyst_df["Enterprise Data Manager"] 
del Social_Science_Analyst_df["Management and Program Analyst"]
del Social_Science_Analyst_df["Public Health Analyst"]
del Social_Science_Analyst_df["Procurement Analyst"]
del Social_Science_Analyst_df["Health Insurance Analyst"]
del Social_Science_Analyst_df["Social Science Analyst"]                                    
Social_Science_Analyst_df

Empty DataFrame
Columns: [Job Title, Company Name, Company Location, Salary, Description, Job Category, city, State, Category]
Index: []

In [21]:
df['Policy Advisor'] = (df["Job Title"].str.lower()
                            .str.contains("policy advisor", regex=False, na=False)
                            .astype(int))


Policy_advisor_df= df.loc[df['Policy Advisor'] == 1]

Policy_advisor_df["Category"] = "Policy Advisor"
del Policy_advisor_df ['Data Analyst']
del Policy_advisor_df ["Computer Scientist"]
del Policy_advisor_df ["IT Specialist"]
del Policy_advisor_df ["Operations Research Analyst"]
del Policy_advisor_df ["Business Intelligence Specialist"]
del Policy_advisor_df ["Research Analyst"]
del Policy_advisor_df ["Data Engineer"]
del Policy_advisor_df["Chief Data Officer"]
del Policy_advisor_df["Enterprise Data Manager"] 
del Policy_advisor_df["Management and Program Analyst"]
del Policy_advisor_df["Public Health Analyst"]
del Policy_advisor_df["Procurement Analyst"]
del Policy_advisor_df["Health Insurance Analyst"]
del Policy_advisor_df["Social Science Analyst"]
del Policy_advisor_df["Policy Advisor"]
Policy_advisor_df

Empty DataFrame
Columns: [Job Title, Company Name, Company Location, Salary, Description, Job Category, city, State, Category]
Index: []

In [22]:
df['Mathematical Analyst'] = (df["Job Title"].str.lower()
                            .str.contains("mathematical analyst", regex=False, na=False)
                            .astype(int))


Mathematical_Analyst_df= df.loc[df['Mathematical Analyst'] == 1]

Mathematical_Analyst_df["Category"] = "Mathematical Analyst"
del Mathematical_Analyst_df ['Data Analyst']
del Mathematical_Analyst_df ["Computer Scientist"]
del Mathematical_Analyst_df ["IT Specialist"]
del Mathematical_Analyst_df ["Operations Research Analyst"]
del Mathematical_Analyst_df ["Business Intelligence Specialist"]
del Mathematical_Analyst_df ["Research Analyst"]
del Mathematical_Analyst_df ["Data Engineer"]
del Mathematical_Analyst_df["Chief Data Officer"]
del Mathematical_Analyst_df["Enterprise Data Manager"] 
del Mathematical_Analyst_df["Management and Program Analyst"]
del Mathematical_Analyst_df["Public Health Analyst"]
del Mathematical_Analyst_df["Procurement Analyst"]
del Mathematical_Analyst_df["Health Insurance Analyst"]
del Mathematical_Analyst_df["Social Science Analyst"]
del Mathematical_Analyst_df["Policy Advisor"]
del Mathematical_Analyst_df["Mathematical Analyst"]
Mathematical_Analyst_df

Empty DataFrame
Columns: [Job Title, Company Name, Company Location, Salary, Description, Job Category, city, State, Category]
Index: []

In [23]:
df['Economic Research Analyst'] = (df["Job Title"].str.lower()
                            .str.contains("economic eesearch enalyst", regex=False, na=False)
                            .astype(int))

Economic_Research_Analyst_df= df.loc[df['Economic Research Analyst'] == 1]

Economic_Research_Analyst_df["Category"] = "Economic Research Analyst"
del Economic_Research_Analyst_df ['Data Analyst']
del Economic_Research_Analyst_df ["Computer Scientist"]
del Economic_Research_Analyst_df ["IT Specialist"]
del Economic_Research_Analyst_df ["Operations Research Analyst"]
del Economic_Research_Analyst_df ["Business Intelligence Specialist"]
del Economic_Research_Analyst_df ["Research Analyst"]
del Economic_Research_Analyst_df ["Data Engineer"]
del Economic_Research_Analyst_df["Chief Data Officer"]
del Economic_Research_Analyst_df["Enterprise Data Manager"] 
del Economic_Research_Analyst_df["Management and Program Analyst"]
del Economic_Research_Analyst_df["Public Health Analyst"]
del Economic_Research_Analyst_df["Procurement Analyst"]
del Economic_Research_Analyst_df["Health Insurance Analyst"]
del Economic_Research_Analyst_df["Social Science Analyst"]
del Economic_Research_Analyst_df["Policy Advisor"]
del Economic_Research_Analyst_df["Mathematical Analyst"]
del Economic_Research_Analyst_df["Economic Research Analyst"]
Economic_Research_Analyst_df

Empty DataFrame
Columns: [Job Title, Company Name, Company Location, Salary, Description, Job Category, city, State, Category]
Index: []

In [24]:
all_dfs = [Data_Analyst_df, Computer_Scientist_df, it_specialist_df, operations_research_analyst_df,
          Research_analyst_df, Management_program_Analyst_df, public_health_Analyst_df, Procurement_Analyst_df]
          

usa_gov_jobs_df = pd.concat(all_dfs).reset_index(drop=True)

In [25]:
usa_gov_jobs_df

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State,Category
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Analyst,Washington,District of Columbia,Data Analyst
1,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Data Analyst,West Roxbury,Massachusetts,Data Analyst
2,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Analyst,Gallup,New Mexico,Data Analyst
3,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Analyst,Gallup,New Mexico,Data Analyst
4,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Engineer,Washington,District of Columbia,Data Analyst
...,...,...,...,...,...,...,...,...,...
1890,Procurement Analyst (Public Notice Flyer),Department of Homeland Security,"Washington, District of Columbia",10369.0,Help\r\n \n...,IT Systems Analyst,Washington,District of Columbia,Procurement Analyst
1891,Contract Specialist/Procurement Analyst - Dire...,Department of Transportation,"Cambridge, Massachusetts",82721.0,Help\r\n \n...,IT Systems Analyst,Cambridge,Massachusetts,Procurement Analyst
1892,Contract Specialist/Procurement Analyst (Direc...,Department of Transportation,No location provided,64009.0,You will serve as a Contract Specialist and ma...,IT Systems Analyst,No location provided,NaN,Procurement Analyst
1893,Contract Specialist/Procurement Analyst (Direc...,Department of Transportation,No location provided,10780.0,You will serve as a Contract Specialist and ma...,IT Systems Analyst,No location provided,NaN,Procurement Analyst
1894,"Contract Spec/Administrator/Negotiator, Procur...",General Services Administration,No location provided,64649.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Procurement Analyst

In [26]:
usa_gov_jobs_df["Category"].unique()

array(['Data Analyst', 'Computer Scientist', 'IT Specialist',
       'Operations Research Analyst', 'Research_Analyst',
       'Management program Analyst', 'Public Health Analyst',
       'Procurement Analyst'], dtype=object)

In [27]:
usa_gov_jobs_df.dropna(axis=1, how='all')

,Job Title,Company Name,Company Location,Salary,Description,Job Category,city,State,Category
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Analyst,Washington,District of Columbia,Data Analyst
1,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,Data Analyst,West Roxbury,Massachusetts,Data Analyst
2,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Analyst,Gallup,New Mexico,Data Analyst
3,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Data Analyst,Gallup,New Mexico,Data Analyst
4,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Data Engineer,Washington,District of Columbia,Data Analyst
...,...,...,...,...,...,...,...,...,...
1890,Procurement Analyst (Public Notice Flyer),Department of Homeland Security,"Washington, District of Columbia",10369.0,Help\r\n \n...,IT Systems Analyst,Washington,District of Columbia,Procurement Analyst
1891,Contract Specialist/Procurement Analyst - Dire...,Department of Transportation,"Cambridge, Massachusetts",82721.0,Help\r\n \n...,IT Systems Analyst,Cambridge,Massachusetts,Procurement Analyst
1892,Contract Specialist/Procurement Analyst (Direc...,Department of Transportation,No location provided,64009.0,You will serve as a Contract Specialist and ma...,IT Systems Analyst,No location provided,NaN,Procurement Analyst
1893,Contract Specialist/Procurement Analyst (Direc...,Department of Transportation,No location provided,10780.0,You will serve as a Contract Specialist and ma...,IT Systems Analyst,No location provided,NaN,Procurement Analyst
1894,"Contract Spec/Administrator/Negotiator, Procur...",General Services Administration,No location provided,64649.0,Help\r\n \n...,IT Systems Analyst,No location provided,NaN,Procurement Analyst

In [28]:
del usa_gov_jobs_df["Job Category"]
usa_gov_jobs_df['Salary']=usa_gov_jobs_df['Salary'].apply(lambda x:round(x,2))

In [29]:
usa_gov_jobs_df["Category"].unique().tolist()

['Data Analyst',
 'Computer Scientist',
 'IT Specialist',
 'Operations Research Analyst',
 'Research_Analyst',
 'Management program Analyst',
 'Public Health Analyst',
 'Procurement Analyst']

In [30]:
usa_gov_jobs_df["Category"].value_counts()

Management program Analyst     632
IT Specialist                  442
Research_Analyst               290
Operations Research Analyst    249
Procurement Analyst            126
Public Health Analyst           63
Data Analyst                    52
Computer Scientist              41
Name: Category, dtype: int64

In [31]:
usa_gov_jobs_df.rename(columns={'Job Title':'Position Title'}, inplace=True)
usa_gov_jobs_df.rename(columns={'Category':'Job Title'}, inplace=True)
usa_gov_jobs_df.rename(columns={'State':'State Name'}, inplace=True)
usa_gov_jobs_df

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Washington,District of Columbia,Data Analyst
1,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498.0,Help\r\n \n...,West Roxbury,Massachusetts,Data Analyst
2,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Gallup,New Mexico,Data Analyst
3,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723.0,Help\r\n \n...,Gallup,New Mexico,Data Analyst
4,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198.0,Help\r\n \n...,Washington,District of Columbia,Data Analyst
...,...,...,...,...,...,...,...,...
1890,Procurement Analyst (Public Notice Flyer),Department of Homeland Security,"Washington, District of Columbia",10369.0,Help\r\n \n...,Washington,District of Columbia,Procurement Analyst
1891,Contract Specialist/Procurement Analyst - Dire...,Department of Transportation,"Cambridge, Massachusetts",82721.0,Help\r\n \n...,Cambridge,Massachusetts,Procurement Analyst
1892,Contract Specialist/Procurement Analyst (Direc...,Department of Transportation,No location provided,64009.0,You will serve as a Contract Specialist and ma...,No location provided,NaN,Procurement Analyst
1893,Contract Specialist/Procurement Analyst (Direc...,Department of Transportation,No location provided,10780.0,You will serve as a Contract Specialist and ma...,No location provided,NaN,Procurement Analyst
1894,"Contract Spec/Administrator/Negotiator, Procur...",General Services Administration,No location provided,64649.0,Help\r\n \n...,No location provided,NaN,Procurement Analyst

In [32]:
usa_gov_jobs_df["Salary"]= usa_gov_jobs_df["Salary"].astype('int')

In [33]:
usa_gov_jobs_df.to_csv("../resources/cpj_usajobcategorized_with_description.csv", index=False)