In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../Resources/cpj_usajobcategorized_with_description.csv")

In [3]:
df

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst
1,Health System Specialist (Data Analyst),Department of Veterans Affairs,"West Roxbury, Massachusetts",59498,Help\r\n \n...,West Roxbury,Massachusetts,Data Analyst
2,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723,Help\r\n \n...,Gallup,New Mexico,Data Analyst
3,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723,Help\r\n \n...,Gallup,New Mexico,Data Analyst
4,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst
...,...,...,...,...,...,...,...,...
1890,Procurement Analyst (Public Notice Flyer),Department of Homeland Security,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Procurement Analyst
1891,Contract Specialist/Procurement Analyst - Dire...,Department of Transportation,"Cambridge, Massachusetts",82721,Help\r\n \n...,Cambridge,Massachusetts,Procurement Analyst
1892,Contract Specialist/Procurement Analyst (Direc...,Department of Transportation,No location provided,64009,You will serve as a Contract Specialist and ma...,No location provided,NaN,Procurement Analyst
1893,Contract Specialist/Procurement Analyst (Direc...,Department of Transportation,No location provided,10780,You will serve as a Contract Specialist and ma...,No location provided,NaN,Procurement Analyst
1894,"Contract Spec/Administrator/Negotiator, Procur...",General Services Administration,No location provided,64649,Help\r\n \n...,No location provided,NaN,Procurement Analyst

In [4]:
df["Python"] = (df["Description"].str.lower()
                            .str.contains("python", regex=False, na=False)
                            .astype(int))
Python_df = df.loc[df["Python"]== 1]
Python_df["Tools"] = "Python"
del Python_df["Python"]
Python_df

<ipython-input-4-47375069c28d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Python_df["Tools"] = "Python"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
95,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Python
96,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Python
116,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Python
117,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Python
136,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Python
...,...,...,...,...,...,...,...,...,...
997,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,Python
1032,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,Python
1033,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,Python
1070,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,Python
1071,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,Python

In [5]:
df["SQL"] = (df["Description"].str.lower()
                            .str.contains("sql", regex=False, na=False)
                            .astype(int))
Sql_df = df.loc[df["SQL"]== 1]
Sql_df["Tools"] = "SQL"
del Sql_df["Python"]
del Sql_df["SQL"]
Sql_df

<ipython-input-5-e1dd65ba6dab>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Sql_df["Tools"] = "SQL"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
4,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
8,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
12,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
16,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
20,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
24,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
28,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
32,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
36,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
40,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
44,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
48,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,SQL
101,IT Specialist (APPSW/DATAMGMT),Other Agencies and Independent Organizations,"Arlington, Virginia",87198,Help\r\n \n...,Arlington,Virginia,IT Specialist,SQL
107,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,SQL
122,IT Specialist (APPSW/DATAMGMT),Other Agencies and Independent Organizations,"Arlington, Virginia",87198,Help\r\n \n...,Arlington,Virginia,IT Specialist,SQL
128,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,SQL
142,IT Specialist (APPSW/DATAMGMT),Other Agencies and Independent Organizations,"Arlington, Virginia",87198,Help\r\n \n...,Arlington,Virginia,IT Specialist,SQL
148,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,SQL
162,IT Specialist (APPSW/DATAMGMT),Other Agencies and Independent Organizations,"Arlington, Virginia",87198,Help\r\n \n...,Arlington,Virginia,IT Specialist,SQL
168,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,SQL
187,IT Specialist (APPSW/DATAMGMT),Other Agencies and Independent Organizations,"Arlington, Virginia",87198,Help\r\n \n...,Arlington,Virginia,IT Specialist,SQL
193,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,SQL
228,IT Specialist (APPSW/DATAMGMT),Other Agencies and Independent Organizations,"Arlington, Virginia",87198,Help\r\n \n...,Arlington,Virginia,IT Specialist,SQL
234,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,SQL
248,IT Specialist (APPSW/DATAMGMT),Other Agencies and Independent Organizations,"Arlington, Virginia",87198,Help\r\n \n...,Arlington,Virginia,IT Specialist,SQL
254,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,SQL
276,IT Specialist,Department of Veterans Affairs,No location provided,66829,Help\r\n \n...,No location provided,NaN,IT Specialist,SQL
292,IT SPECIALIST (APPSW),Department of Agriculture,"New Orleans, Louisiana",77488,Help\r\n \n...,New Orleans,Louisiana,IT Specialist,SQL
293,IT Specialist,Department of Veterans Affairs,No location provided,55756,Help\r\n \n...,No location provided,NaN,IT Specialist,SQL
314,IT SPECIALIST (APPSW),Department of Defense,No location provided,78136,Help\r\n \n...,No location provided,NaN,IT Specialist,SQL
315,IT SPECIALIST (APPSW),Department of Defense,No location provided,78136,Help\r\n \n...,No location provided,NaN,IT Specialist,SQL
317,IT SPECIALIST (APPSW),Department of Defense,"Indianapolis, Indiana",78136,Help\r\n \n...,Indianapolis,Indiana,IT Specialist,SQL
318,IT SPECIALIST (APPSW),Department of Defense,"Fort Belvoir, Virginia",10369,Help\r\n \n...,Fort Belvoir,Virginia,IT Specialist,SQL
319,IT Specialist (Appsw),Department of Defense,"Fort Belvoir, Virginia",10369,Help\r\n \n...,Fort Belvoir,Virginia,IT Specialist,SQL
320,IT SPECIALIST (APPSW),Department of Defense,"Indianapolis, Indiana",78136,Help\r\n \n...,Indianapolis,Indiana,IT Specialist,SQL
326,IT Specialist (INET),Department of Homeland Security,"Bothell, Washington",84886,Help\r\n \n...,Bothell,Washington,IT Specialist,SQL
337,IT Specialist (APPSW),Department of the Army,"Key West, Florida",46531,Help\r\n \n...,Key West,Florida,IT Specialist,SQL
339,IT SPECIALIST (APPSW),Department of Defense,"Indianapolis, Indiana",78136,Help\r\n \n...,Indianapolis,Indiana,IT Specialist,SQL
340,IT SPECIALIST (APPSW),Department of Defense,"Indianapolis, Indiana",78136,Help\r\n \n...,Indianapolis,Indiana,IT Specialist,SQL
350,IT Specialist,Department of Energy,"Portland, Oregon",98334,Help\r\n \n...,Portland,Oregon,IT Specialist,SQL
351,IT Specialist,Department of Energy,"Portland, Oregon",98334,Help\r\n \n...,Portland,Oregon,IT Specialist,SQL
360,IT Specialist (APPSW),Department of the Treasury,No location provided,92143,Help\r\n \n...,No location provided,NaN,IT Specialist,SQL
382,IT SPECIALIST (APPSW) (Title 5),Department of the Army,"Camp Mabry, Texas",65792,Help\r\n \n...,Camp Mabry,Texas,IT Specialist,SQL
387,IT SPECIALIST (INFOSEC/APPSW),Department of Defense,"Offutt AFB, Nebraska",77742,Help\r\n \n...,Offutt AFB,Nebraska,IT Specialist,SQL
394,IT SPECIALIST (INFOSEC/APPSW),Department of Defense,"Offutt AFB, Nebraska",77742,Help\r\n \n...,Offutt AFB,Nebraska,IT Specialist,SQL
417,IT Specialist (APPSW/DATAMGMT),Other Agencies and Independent Organizations,"Arlington, Virginia",87198,Help\r\n \n...,Arlington,Virginia,IT Specialist,SQL
435,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,SQL
491,IT Specialist (System Administration),Department of Transportation,"Oklahoma City, Oklahoma",78388,Help\r\n \n...,Oklahoma City,Oklahoma,IT Specialist,SQL
492,IT Specialist (System Administration),Department of Transportation,"Oklahoma City, Oklahoma",78388,Help\r\n \n...,Oklahoma City,Oklahoma,IT Specialist,SQL

In [6]:
df["Spark"] = (df["Description"].str.lower()
                            .str.contains("Spark", regex=False, na=False)
                            .astype(int))
Spark_df = df.loc[df["Spark"]== 1]
Spark_df["Tools"] = "Spark"
del Spark_df["Python"]
del Spark_df["SQL"]
del Spark_df["Spark"]
Spark_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [7]:
df["JavaScript"] = (df["Description"].str.lower()
                            .str.contains("JavaScript", regex=False, na=False)
                            .astype(int))
JavaScript_df = df.loc[df["JavaScript"]== 1]
JavaScript_df["Tools"] = "JavaScript"
del JavaScript_df["Python"]
del JavaScript_df["SQL"]
del JavaScript_df["Spark"]
del JavaScript_df["JavaScript"]
JavaScript_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [8]:
df["R"] = (df["Description"].str.upper()
                            .str.contains(" R ", regex=False, na=False)
                            .astype(int))
R_df = df.loc[df["R"]== 1]
R_df["Tools"] = "R"
del R_df["Python"]
del R_df["SQL"]
del R_df["Spark"]
del R_df["JavaScript"]
del R_df["R"]
R_df

<ipython-input-8-30d615fef138>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  R_df["Tools"] = "R"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
377,IT SPECIALIST (SYSANALYSIS),Department of the Navy,"Saint Inigoes, Maryland",87198,Help\r\n \n...,Saint Inigoes,Maryland,IT Specialist,R
535,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
536,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
568,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
569,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
572,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
573,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
574,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
575,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
576,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
577,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
611,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
612,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
644,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
645,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
677,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
678,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
710,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
711,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
714,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
715,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
716,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
717,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
747,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
748,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
780,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
781,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,R
785,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
786,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
823,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
824,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
827,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
828,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
831,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
832,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
834,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
835,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
874,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
875,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
912,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
913,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
950,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
951,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
988,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
989,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
993,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
994,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
996,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
997,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
1032,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
1033,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
1070,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R
1071,Operations Research Analyst (Senior Financial ...,Department of the Treasury,No location provided,13755,Help\r\n \n...,No location provided,NaN,Research_Analyst,R

In [9]:
df["NoSQL"] = (df["Description"].str.lower()
                            .str.contains("nosql", regex=False, na=False)
                            .astype(int))
NoSql_df = df.loc[df["NoSQL"]== 1]
NoSql_df["Tools"] = "NoSQL"
del NoSql_df["Python"]
del NoSql_df["SQL"]
del NoSql_df["Spark"]
del NoSql_df["JavaScript"]
del NoSql_df["NoSQL"]
del NoSql_df["R"]
NoSql_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [10]:
df["AWS"] = (df["Description"].str.lower()
                            .str.contains("AWS", regex=False, na=False)
                            .astype(int))
Aws_df = df.loc[df["AWS"]== 1]
Aws_df["Tools"] = "AWS"
del Aws_df["Python"]
del Aws_df["SQL"]
del Aws_df["Spark"]
del Aws_df["JavaScript"]
del Aws_df["NoSQL"]
del Aws_df["AWS"]
del Aws_df["R"]
Aws_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [11]:
df["Azure"] = (df["Description"].str.lower()
                            .str.contains("azure", regex=False, na=False)
                            .astype(int))
Azure_df = df.loc[df["Azure"]== 1]
Azure_df["Tools"] = "Azure"
del Azure_df["Python"]
del Azure_df["SQL"]
del Azure_df["Spark"]
del Azure_df["JavaScript"]
del Azure_df["NoSQL"]
del Azure_df["AWS"]
del Azure_df["Azure"]
del Azure_df["R"]
Azure_df

<ipython-input-11-4a4842079acc>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Azure_df["Tools"] = "Azure"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
112,"Senior IT Specialist, (DATAMGT) CG-2210-15 TEM...",Other Agencies and Independent Organizations,"Washington, District of Columbia",12962,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Azure
133,"Senior IT Specialist, (DATAMGT) CG-2210-15 TEM...",Other Agencies and Independent Organizations,"Washington, District of Columbia",12962,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Azure
153,"Senior IT Specialist, (DATAMGT) CG-2210-15 TEM...",Other Agencies and Independent Organizations,"Washington, District of Columbia",12962,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Azure
174,"Senior IT Specialist, (DATAMGT) CG-2210-15 TEM...",Other Agencies and Independent Organizations,"Washington, District of Columbia",12962,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Azure
199,"Senior IT Specialist, (DATAMGT) CG-2210-15 TEM...",Other Agencies and Independent Organizations,"Washington, District of Columbia",12962,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Azure
239,"Senior IT Specialist, (DATAMGT) CG-2210-15 TEM...",Other Agencies and Independent Organizations,"Washington, District of Columbia",12962,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Azure
259,"Senior IT Specialist, (DATAMGT) CG-2210-15 TEM...",Other Agencies and Independent Organizations,"Washington, District of Columbia",12962,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Azure
316,IT SPECIALIST (APPSW),Department of the Interior,No location provided,92143,Help\r\n \n...,No location provided,NaN,IT Specialist,Azure
318,IT SPECIALIST (APPSW),Department of Defense,"Fort Belvoir, Virginia",10369,Help\r\n \n...,Fort Belvoir,Virginia,IT Specialist,Azure
319,IT Specialist (Appsw),Department of Defense,"Fort Belvoir, Virginia",10369,Help\r\n \n...,Fort Belvoir,Virginia,IT Specialist,Azure
360,IT Specialist (APPSW),Department of the Treasury,No location provided,92143,Help\r\n \n...,No location provided,NaN,IT Specialist,Azure
394,IT SPECIALIST (INFOSEC/APPSW),Department of Defense,"Offutt AFB, Nebraska",77742,Help\r\n \n...,Offutt AFB,Nebraska,IT Specialist,Azure
468,IT Specialist (SYSADMIN/INFOSEC),Department of Defense,"Pearl Harbor, Hawaii",86584,Help\r\n \n...,Pearl Harbor,Hawaii,IT Specialist,Azure
531,"Senior IT Specialist, (DATAMGT) CG-2210-15 TEM...",Other Agencies and Independent Organizations,"Washington, District of Columbia",12962,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Azure

In [12]:
df["Google Cloud"] = (df["Description"].str.lower()
                            .str.contains("google cloud", regex=False, na=False)
                            .astype(int))
Google_Cloud_df = df.loc[df["Google Cloud"]== 1]
Google_Cloud_df["Tools"] = "Google Cloud"
del Google_Cloud_df["Python"]
del Google_Cloud_df["SQL"]
del Google_Cloud_df["Spark"]
del Google_Cloud_df["JavaScript"]
del Google_Cloud_df["NoSQL"]
del Google_Cloud_df["AWS"]
del Google_Cloud_df["Azure"]
del Google_Cloud_df["Google Cloud"]
del Google_Cloud_df["R"]
Google_Cloud_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [13]:
df["Cloud"] = (df["Description"].str.lower()
                            .str.contains("Cloud", regex=False, na=False)
                            .astype(int))
Cloud_df = df.loc[df["Cloud"]== 1]
Cloud_df["Tools"] = "Cloud"
del Cloud_df["Python"]
del Cloud_df["SQL"]
del Cloud_df["Spark"]
del Cloud_df["JavaScript"]
del Cloud_df["NoSQL"]
del Cloud_df["AWS"]
del Cloud_df["Azure"]
del Cloud_df["Google Cloud"]
del Cloud_df["Cloud"]
del Cloud_df["R"]
Cloud_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [14]:
df["HTML"] = (df["Description"].str.lower()
                            .str.contains("html", regex=False, na=False)
                            .astype(int))
Html_df = df.loc[df["HTML"]== 1]
Html_df["Tools"] = "HTML"
del Html_df["Python"]
del Html_df["SQL"]
del Html_df["Spark"]
del Html_df["JavaScript"]
del Html_df["NoSQL"]
del Html_df["AWS"]
del Html_df["Azure"]
del Html_df["Google Cloud"]
del Html_df["Cloud"]
del Html_df["HTML"]
del Html_df["R"]
Html_df

<ipython-input-14-2510091f0abe>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Html_df["Tools"] = "HTML"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
2,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723,Help\r\n \n...,Gallup,New Mexico,Data Analyst,HTML
3,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723,Help\r\n \n...,Gallup,New Mexico,Data Analyst,HTML
6,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723,Help\r\n \n...,Gallup,New Mexico,Data Analyst,HTML
7,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723,Help\r\n \n...,Gallup,New Mexico,Data Analyst,HTML
10,Supervisory Performance Improvement / Data Ana...,Department of Health And Human Services,"Gallup, New Mexico",92723,Help\r\n \n...,Gallup,New Mexico,Data Analyst,HTML
...,...,...,...,...,...,...,...,...,...
1877,Procurement Analyst,Department of the Army,"Mobile, Alabama",92143,Help\r\n \n...,Mobile,Alabama,Procurement Analyst,HTML
1879,Procurement Analyst,General Services Administration,"Lakewood, Colorado",10102,Help\r\n \n...,Lakewood,Colorado,Procurement Analyst,HTML
1882,PROCUREMENT ANALYST,Department of the Army,"Fort Bragg, North Carolina",95751,Help\r\n \n...,Fort Bragg,North Carolina,Procurement Analyst,HTML
1883,Procurement Analyst,Department of Health And Human Services,No location provided,66829,Help\r\n \n...,No location provided,NaN,Procurement Analyst,HTML
1894,"Contract Spec/Administrator/Negotiator, Procur...",General Services Administration,No location provided,64649,Help\r\n \n...,No location provided,NaN,Procurement Analyst,HTML

In [15]:
df["CSS"] = (df["Description"].str.lower()
                            .str.contains("css", regex=False, na=False)
                            .astype(int))
css_df = df.loc[df["CSS"]== 1]
css_df["Tools"] = "CSS"
del css_df["Python"]
del css_df["SQL"]
del css_df["Spark"]
del css_df["JavaScript"]
del css_df["NoSQL"]
del css_df["AWS"]
del css_df["Azure"]
del css_df["Google Cloud"]
del css_df["Cloud"]
del css_df["HTML"]
del css_df["CSS"]
del css_df["R"]
css_df

<ipython-input-15-2547a7a6ca3a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  css_df["Tools"] = "CSS"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
107,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,CSS
128,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,CSS
148,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,CSS
168,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,CSS
193,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,CSS
234,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,CSS
254,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,CSS
318,IT SPECIALIST (APPSW),Department of Defense,"Fort Belvoir, Virginia",10369,Help\r\n \n...,Fort Belvoir,Virginia,IT Specialist,CSS
337,IT Specialist (APPSW),Department of the Army,"Key West, Florida",46531,Help\r\n \n...,Key West,Florida,IT Specialist,CSS
392,IT Specialist (INFOSEC),Department of Defense,No location provided,87198,Help\r\n \n...,No location provided,NaN,IT Specialist,CSS
399,IT SPECIALIST (INFOSEC),Department of the Air Force,"Fort Meade, Maryland",10369,Help\r\n \n...,Fort Meade,Maryland,IT Specialist,CSS
435,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,CSS
491,IT Specialist (System Administration),Department of Transportation,"Oklahoma City, Oklahoma",78388,Help\r\n \n...,Oklahoma City,Oklahoma,IT Specialist,CSS
492,IT Specialist (System Administration),Department of Transportation,"Oklahoma City, Oklahoma",78388,Help\r\n \n...,Oklahoma City,Oklahoma,IT Specialist,CSS
503,SUPERVISORY IT SPECIALIST (INFOSEC),Department of the Air Force,"Fort Meade, Maryland",12253,Help\r\n \n...,Fort Meade,Maryland,IT Specialist,CSS

In [16]:
df["DataBricks"] = (df["Description"].str.lower()
                            .str.contains("databricks", regex=False, na=False)
                            .astype(int))
Databricks_df = df.loc[df["DataBricks"]== 1]
Databricks_df["Tools"] = "DataBricks"
del Databricks_df["Python"]
del Databricks_df["SQL"]
del Databricks_df["Spark"]
del Databricks_df["JavaScript"]
del Databricks_df["NoSQL"]
del Databricks_df["AWS"]
del Databricks_df["Azure"]
del Databricks_df["Google Cloud"]
del Databricks_df["Cloud"]
del Databricks_df["HTML"]
del Databricks_df["CSS"]
del Databricks_df["R"]
del Databricks_df["DataBricks"]
Databricks_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [17]:
df["Snowflake"] = (df["Description"].str.lower()
                            .str.contains("snowflake", regex=False, na=False)
                            .astype(int))
Snowflake_df = df.loc[df["Snowflake"]== 1]
Snowflake_df["Tools"] = "Snowflake"
del Snowflake_df["Python"]
del Snowflake_df["SQL"]
del Snowflake_df["Spark"]
del Snowflake_df["JavaScript"]
del Snowflake_df["NoSQL"]
del Snowflake_df["AWS"]
del Snowflake_df["Azure"]
del Snowflake_df["Google Cloud"]
del Snowflake_df["Cloud"]
del Snowflake_df["HTML"]
del Snowflake_df["CSS"]
del Snowflake_df["Snowflake"]
del Snowflake_df["R"]
del Snowflake_df["DataBricks"]
Snowflake_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [18]:
df["PyTorch"] = (df["Description"].str.lower()
                            .str.contains("pytorch", regex=False, na=False)
                            .astype(int))
PyTorch_df = df.loc[df["PyTorch"]== 1]
PyTorch_df["Tools"] = "PyTorch"
del PyTorch_df["Python"]
del PyTorch_df["SQL"]
del PyTorch_df["Spark"]
del PyTorch_df["JavaScript"]
del PyTorch_df["NoSQL"]
del PyTorch_df["AWS"]
del PyTorch_df["Azure"]
del PyTorch_df["Google Cloud"]
del PyTorch_df["Cloud"]
del PyTorch_df["HTML"]
del PyTorch_df["CSS"]
del PyTorch_df["Snowflake"]
del PyTorch_df["R"]
del PyTorch_df["PyTorch"]

PyTorch_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, DataBricks, Tools]
Index: []

In [19]:
df["GCP"] = (df["Description"].str.lower()
                            .str.contains("gcp", regex=False, na=False)
                            .astype(int))
Gcp_df = df.loc[df["GCP"]== 1]
Gcp_df["Tools"] = "GCP"
del Gcp_df["Python"]
del Gcp_df["SQL"]
del Gcp_df["Spark"]
del Gcp_df["JavaScript"]
del Gcp_df["NoSQL"]
del Gcp_df["AWS"]
del Gcp_df["Azure"]
del Gcp_df["Google Cloud"]
del Gcp_df["Cloud"]
del Gcp_df["HTML"]
del Gcp_df["CSS"]
del Gcp_df["Snowflake"]
del Gcp_df["DataBricks"]
del Gcp_df["PyTorch"]
del Gcp_df["GCP"]
del Gcp_df["R"]

Gcp_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [20]:
df["Excel"] = (df["Description"].str.lower()
                            .str.contains("excel", regex=False, na=False)
                            .astype(int))
Excel_df = df.loc[df["Excel"]== 1]
Excel_df["Tools"] = "Excel"
del Excel_df["Python"]
del Excel_df["SQL"]
del Excel_df["Spark"]
del Excel_df["JavaScript"]
del Excel_df["NoSQL"]
del Excel_df["AWS"]
del Excel_df["Azure"]
del Excel_df["Google Cloud"]
del Excel_df["Cloud"]
del Excel_df["HTML"]
del Excel_df["CSS"]
del Excel_df["Snowflake"]
del Excel_df["DataBricks"]
del Excel_df["PyTorch"]
del Excel_df["GCP"]
del Excel_df["Excel"]
del Excel_df["R"]
Excel_df

<ipython-input-20-799e6dbde0dc>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Excel_df["Tools"] = "Excel"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
53,"Computer Engineer, Computer Scientist, Electri...",Other Agencies and Independent Organizations,"Rockville, Maryland",12253,Help\r\n \n...,Rockville,Maryland,Computer Scientist,Excel
75,"Computer Engineer, Computer Scientist, Electri...",Other Agencies and Independent Organizations,"Rockville, Maryland",12253,Help\r\n \n...,Rockville,Maryland,Computer Scientist,Excel
77,"Computer Engineer, Computer Scientist, Electri...",Other Agencies and Independent Organizations,"Rockville, Maryland",12253,Help\r\n \n...,Rockville,Maryland,Computer Scientist,Excel
82,"Computer Engineer, Computer Scientist, Electri...",Other Agencies and Independent Organizations,"Rockville, Maryland",12253,Help\r\n \n...,Rockville,Maryland,Computer Scientist,Excel
95,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Excel
...,...,...,...,...,...,...,...,...,...
1818,Procurement Analyst (Public Notice Flyer),Department of Homeland Security,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Procurement Analyst,Excel
1836,Procurement Analyst (Public Notice Flyer),Department of Homeland Security,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Procurement Analyst,Excel
1854,Procurement Analyst (Public Notice Flyer),Department of Homeland Security,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Procurement Analyst,Excel
1872,Procurement Analyst (Public Notice Flyer),Department of Homeland Security,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Procurement Analyst,Excel
1890,Procurement Analyst (Public Notice Flyer),Department of Homeland Security,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Procurement Analyst,Excel

In [21]:
df["VBA"] = (df["Description"].str.lower()
                            .str.contains("vba", regex=False, na=False)
                            .astype(int))
Vba_df = df.loc[df["VBA"]== 1]
Vba_df["Tools"] = "VBA"
del Vba_df["Python"]
del Vba_df["SQL"]
del Vba_df["Spark"]
del Vba_df["JavaScript"]
del Vba_df["NoSQL"]
del Vba_df["AWS"]
del Vba_df["Azure"]
del Vba_df["Google Cloud"]
del Vba_df["Cloud"]
del Vba_df["HTML"]
del Vba_df["CSS"]
del Vba_df["Snowflake"]
del Vba_df["DataBricks"]
del Vba_df["PyTorch"]
del Vba_df["GCP"]
del Vba_df["Excel"]
del Vba_df["VBA"]
del Vba_df["R"]
Vba_df

<ipython-input-21-d926b59e66c5>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Vba_df["Tools"] = "VBA"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
1114,Management and Program Analyst,Department of Veterans Affairs,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,VBA
1207,Management and Program Analyst,Department of Veterans Affairs,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,VBA
1295,Management and Program Analyst,Department of Veterans Affairs,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,VBA
1385,Management and Program Analyst,Department of Veterans Affairs,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,VBA
1473,Management and Program Analyst,Department of Veterans Affairs,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,VBA
1568,Management and Program Analyst,Department of Veterans Affairs,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,VBA
1657,Management and Program Analyst,Department of Veterans Affairs,"Washington, District of Columbia",10369,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,VBA

In [22]:
df["PowerBI"] = (df["Description"].str.lower()
                            .str.contains("powerbi", regex=False, na=False)
                            .astype(int))
PowerBI_df = df.loc[df["PowerBI"]== 1]
PowerBI_df["Tools"] = "PowerBI"
del PowerBI_df["Python"]
del PowerBI_df["SQL"]
del PowerBI_df["Spark"]
del PowerBI_df["JavaScript"]
del PowerBI_df["NoSQL"]
del PowerBI_df["AWS"]
del PowerBI_df["Azure"]
del PowerBI_df["Google Cloud"]
del PowerBI_df["Cloud"]
del PowerBI_df["HTML"]
del PowerBI_df["CSS"]
del PowerBI_df["Snowflake"]
del PowerBI_df["DataBricks"]
del PowerBI_df["PyTorch"]
del PowerBI_df["GCP"]
del PowerBI_df["Excel"]
del PowerBI_df["VBA"]
del PowerBI_df["PowerBI"]
del PowerBI_df["R"]
PowerBI_df

<ipython-input-22-54c36644a965>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PowerBI_df["Tools"] = "PowerBI"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
316,IT SPECIALIST (APPSW),Department of the Interior,No location provided,92143,Help\r\n \n...,No location provided,NaN,IT Specialist,PowerBI

In [23]:
df["Tableau"] = (df["Description"].str.lower()
                            .str.contains("tableau", regex=False, na=False)
                            .astype(int))
Tableau_df = df.loc[df["Tableau"]== 1]
Tableau_df["Tools"] = "Tableau"
del Tableau_df["Python"]
del Tableau_df["SQL"]
del Tableau_df["Spark"]
del Tableau_df["JavaScript"]
del Tableau_df["NoSQL"]
del Tableau_df["AWS"]
del Tableau_df["Azure"]
del Tableau_df["Google Cloud"]
del Tableau_df["Cloud"]
del Tableau_df["HTML"]
del Tableau_df["CSS"]
del Tableau_df["Snowflake"]
del Tableau_df["DataBricks"]
del Tableau_df["PyTorch"]
del Tableau_df["GCP"]
del Tableau_df["Excel"]
del Tableau_df["VBA"]
del Tableau_df["PowerBI"]
del Tableau_df["Tableau"]
del Tableau_df["R"]
Tableau_df

<ipython-input-23-1dfa79ea0cf1>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tableau_df["Tools"] = "Tableau"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
0,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
4,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
8,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
12,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
16,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
20,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
24,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
28,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
32,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
36,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
40,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
44,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
48,Data Analyst,Other Agencies and Independent Organizations,"Washington, District of Columbia",87198,Help\r\n \n...,Washington,District of Columbia,Data Analyst,Tableau
335,IT SPECIALIST (APPSW),Department of the Navy,"Naval Support Activity, Mechanicsburg, Pennsyl...",78324,Help\r\n \n...,Naval Support Activity,Pennsylvania,IT Specialist,Tableau

In [24]:
df["Hadoop"] = (df["Description"].str.lower()
                            .str.contains("hadoop", regex=False, na=False)
                            .astype(int))
Hadoop_df = df.loc[df["Hadoop"]== 1]
Hadoop_df["Tools"] = "Hadoop"
del Hadoop_df["Python"]
del Hadoop_df["SQL"]
del Hadoop_df["Spark"]
del Hadoop_df["JavaScript"]
del Hadoop_df["NoSQL"]
del Hadoop_df["AWS"]
del Hadoop_df["Azure"]
del Hadoop_df["Google Cloud"]
del Hadoop_df["Cloud"]
del Hadoop_df["HTML"]
del Hadoop_df["CSS"]
del Hadoop_df["Snowflake"]
del Hadoop_df["DataBricks"]
del Hadoop_df["PyTorch"]
del Hadoop_df["GCP"]
del Hadoop_df["Excel"]
del Hadoop_df["VBA"]
del Hadoop_df["PowerBI"]
del Hadoop_df["Tableau"]
del Hadoop_df["Hadoop"]
del Hadoop_df["R"]
Hadoop_df

<ipython-input-24-04f3efe7d83f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hadoop_df["Tools"] = "Hadoop"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
105,IT SPECIALIST (DATA MANAGEMENT),Department of Defense,"Bethesda, Maryland",10369,Help\r\n \n...,Bethesda,Maryland,IT Specialist,Hadoop
126,IT SPECIALIST (DATA MANAGEMENT),Department of Defense,"Bethesda, Maryland",10369,Help\r\n \n...,Bethesda,Maryland,IT Specialist,Hadoop
146,IT SPECIALIST (DATA MANAGEMENT),Department of Defense,"Bethesda, Maryland",10369,Help\r\n \n...,Bethesda,Maryland,IT Specialist,Hadoop
166,IT SPECIALIST (DATA MANAGEMENT),Department of Defense,"Bethesda, Maryland",10369,Help\r\n \n...,Bethesda,Maryland,IT Specialist,Hadoop
191,IT SPECIALIST (DATA MANAGEMENT),Department of Defense,"Bethesda, Maryland",10369,Help\r\n \n...,Bethesda,Maryland,IT Specialist,Hadoop
232,IT SPECIALIST (DATA MANAGEMENT),Department of Defense,"Bethesda, Maryland",10369,Help\r\n \n...,Bethesda,Maryland,IT Specialist,Hadoop
252,IT SPECIALIST (DATA MANAGEMENT),Department of Defense,"Bethesda, Maryland",10369,Help\r\n \n...,Bethesda,Maryland,IT Specialist,Hadoop
431,IT SPECIALIST (DATA MANAGEMENT),Department of Defense,"Bethesda, Maryland",10369,Help\r\n \n...,Bethesda,Maryland,IT Specialist,Hadoop

In [25]:
df["Scala"] = (df["Description"].str.lower()
                            .str.contains("scala", regex=False, na=False)
                            .astype(int))
Scala_df = df.loc[df["Scala"]== 1]
Scala_df["Tools"] = "Scala"
del Scala_df["Python"]
del Scala_df["SQL"]
del Scala_df["Spark"]
del Scala_df["JavaScript"]
del Scala_df["NoSQL"]
del Scala_df["AWS"]
del Scala_df["Azure"]
del Scala_df["Google Cloud"]
del Scala_df["Cloud"]
del Scala_df["HTML"]
del Scala_df["CSS"]
del Scala_df["Snowflake"]
del Scala_df["DataBricks"]
del Scala_df["PyTorch"]
del Scala_df["GCP"]
del Scala_df["Excel"]
del Scala_df["VBA"]
del Scala_df["PowerBI"]
del Scala_df["Tableau"]
del Scala_df["Hadoop"]
del Scala_df["Scala"]
del Scala_df["R"]
Scala_df

<ipython-input-25-3882d189063d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Scala_df["Tools"] = "Scala"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
56,Interdisciplinary Computer Engineer / Computer...,Legislative Branch,"Washington, District of Columbia",10840,Help\r\n \n...,Washington,District of Columbia,Computer Scientist,Scala
70,Interdisciplinary Computer Engineer / Computer...,Legislative Branch,"Washington, District of Columbia",10840,Help\r\n \n...,Washington,District of Columbia,Computer Scientist,Scala
80,Interdisciplinary Computer Engineer / Computer...,Legislative Branch,"Washington, District of Columbia",10840,Help\r\n \n...,Washington,District of Columbia,Computer Scientist,Scala
85,Interdisciplinary Computer Engineer / Computer...,Legislative Branch,"Washington, District of Columbia",10840,Help\r\n \n...,Washington,District of Columbia,Computer Scientist,Scala
100,IT SPECIALIST (DATAMGT) (T32),Department of the Army,"Montgomery, Alabama",65792,Help\r\n \n...,Montgomery,Alabama,IT Specialist,Scala
113,IT Specialist (Helpdesk Analyst) NF3,Department of the Navy,"Quantico, Virginia",35000,Help\r\n \n...,Quantico,Virginia,IT Specialist,Scala
121,IT SPECIALIST (DATAMGT) (T32),Department of the Army,"Montgomery, Alabama",65792,Help\r\n \n...,Montgomery,Alabama,IT Specialist,Scala
141,IT SPECIALIST (DATAMGT) (T32),Department of the Army,"Montgomery, Alabama",65792,Help\r\n \n...,Montgomery,Alabama,IT Specialist,Scala
161,IT SPECIALIST (DATAMGT) (T32),Department of the Army,"Montgomery, Alabama",65792,Help\r\n \n...,Montgomery,Alabama,IT Specialist,Scala
178,IT Specialist (Application Software),Department of Transportation,No location provided,83458,Help\r\n \n...,No location provided,NaN,IT Specialist,Scala
186,IT SPECIALIST (DATAMGT) (T32),Department of the Army,"Montgomery, Alabama",65792,Help\r\n \n...,Montgomery,Alabama,IT Specialist,Scala
200,IT Specialist (Helpdesk Analyst) NF3,Department of the Navy,"Quantico, Virginia",35000,Help\r\n \n...,Quantico,Virginia,IT Specialist,Scala
202,IT Specialist (Helpdesk Analyst) NF3,Department of the Navy,"Quantico, Virginia",35000,Help\r\n \n...,Quantico,Virginia,IT Specialist,Scala
208,IT SPECIALIST(Operating Systems),Department of the Navy,"Naval Air Station Pensacola , Florida",92143,Help\r\n \n...,Naval Air Station Pensacola,Florida,IT Specialist,Scala
216,IT Specialist (Helpdesk Analyst) NF3,Department of the Navy,"Quantico, Virginia",35000,Help\r\n \n...,Quantico,Virginia,IT Specialist,Scala
218,IT Specialist (Helpdesk Analyst) NF3,Department of the Navy,"Quantico, Virginia",35000,Help\r\n \n...,Quantico,Virginia,IT Specialist,Scala
227,IT SPECIALIST (DATAMGT) (T32),Department of the Army,"Montgomery, Alabama",65792,Help\r\n \n...,Montgomery,Alabama,IT Specialist,Scala
247,IT SPECIALIST (DATAMGT) (T32),Department of the Army,"Montgomery, Alabama",65792,Help\r\n \n...,Montgomery,Alabama,IT Specialist,Scala
260,IT Specialist (Helpdesk Analyst) NF3,Department of the Navy,"Quantico, Virginia",35000,Help\r\n \n...,Quantico,Virginia,IT Specialist,Scala
262,IT Specialist (Helpdesk Analyst) NF3,Department of the Navy,"Quantico, Virginia",35000,Help\r\n \n...,Quantico,Virginia,IT Specialist,Scala
269,IT SPECIALIST(Operating Systems),Department of the Navy,"Naval Air Station Pensacola , Florida",92143,Help\r\n \n...,Naval Air Station Pensacola,Florida,IT Specialist,Scala
285,IT Specialist,Department of Veterans Affairs,No location provided,66829,Help\r\n \n...,No location provided,NaN,IT Specialist,Scala
286,IT Specialist,Department of Veterans Affairs,No location provided,66829,Help\r\n \n...,No location provided,NaN,IT Specialist,Scala
287,IT Specialist,Department of Veterans Affairs,No location provided,66829,Help\r\n \n...,No location provided,NaN,IT Specialist,Scala
288,IT Specialist,Department of Veterans Affairs,No location provided,66829,Help\r\n \n...,No location provided,NaN,IT Specialist,Scala
289,IT Specialist,Department of Veterans Affairs,No location provided,66829,Help\r\n \n...,No location provided,NaN,IT Specialist,Scala
290,IT Specialist,Department of Veterans Affairs,No location provided,66829,Help\r\n \n...,No location provided,NaN,IT Specialist,Scala
371,IT SPECIALIST (DATAMGT) (T32),Department of the Army,"Montgomery, Alabama",65792,Help\r\n \n...,Montgomery,Alabama,IT Specialist,Scala
441,IT Specialist (SYSADMIN/PLCYPLN),Department of the Army,"Picatinny Arsenal, New Jersey",12581,Help\r\n \n...,Picatinny Arsenal,New Jersey,IT Specialist,Scala
455,IT Specialist (Network Services),Department of Agriculture,No location provided,77488,Help\r\n \n...,No location provided,NaN,IT Specialist,Scala
471,IT Specialist (Application Software),Department of Transportation,No location provided,83458,Help\r\n \n...,No location provided,NaN,IT Specialist,Scala
1086,Management and Program Analyst,Executive Office of the President,"Washington, District of Columbia",12253,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,Scala
1160,SUPERVISORY MANAGEMENT AND PROGRAM ANALYST (Ch...,Department of Homeland Security,No location provided,93907,Help\r\n \n...,No location provided,NaN,Management program Analyst,Scala
1179,Management and Program Analyst,Executive Office of the President,"Washington, District of Columbia",12253,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,Scala
1253,SUPERVISORY MANAGEMENT AND PROGRAM ANALYST (Ch...,Department of Homeland Security,No location provided,93907,Help\r\n \n...,No location provided,NaN,Management program Analyst,Scala
1267,Management and Program Analyst,Executive Office of the President,"Washington, District of Columbia",12253,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,Scala
1342,SUPERVISORY MANAGEMENT AND PROGRAM ANALYST (Ch...,Department of Homeland Security,No location provided,93907,Help\r\n \n...,No location provided,NaN,Management program Analyst,Scala
1357,Management and Program Analyst,Executive Office of the President,"Washington, District of Columbia",12253,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,Scala
1431,SUPERVISORY MANAGEMENT AND PROGRAM ANALYST (Ch...,Department of Homeland Security,No location provided,93907,Help\r\n \n...,No location provided,NaN,Management program Analyst,Scala
1445,Management and Program Analyst,Executive Office of the President,"Washington, District of Columbia",12253,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,Scala
1520,SUPERVISORY MANAGEMENT AND PROGRAM ANALYST (Ch...,Department of Homeland Security,No location provided,93907,Help\r\n \n...,No location provided,NaN,Management program Analyst,Scala
1540,Management and Program Analyst,Executive Office of the President,"Washington, District of Columbia",12253,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,Scala
1615,SUPERVISORY MANAGEMENT AND PROGRAM ANALYST (Ch...,Department of Homeland Security,No location provided,93907,Help\r\n \n...,No location provided,NaN,Management program Analyst,Scala
1629,Management and Program Analyst,Executive Office of the President,"Washington, District of Columbia",12253,Help\r\n \n...,Washington,District of Columbia,Management program Analyst,Scala
1703,SUPERVISORY MANAGEMENT AND PROGRAM ANALYST (Ch...,Department of Homeland Security,No location provided,93907,Help\r\n \n...,No location provided,NaN,Management program Analyst,Scala

In [26]:
df["Java"] = (df["Description"].str.lower()
                            .str.contains("java", regex=False, na=False)
                            .astype(int))
Java_df = df.loc[df["Java"]== 1]
Java_df["Tools"] = "Java"
del Java_df["Python"]
del Java_df["SQL"]
del Java_df["Spark"]
del Java_df["JavaScript"]
del Java_df["NoSQL"]
del Java_df["AWS"]
del Java_df["Azure"]
del Java_df["Google Cloud"]
del Java_df["Cloud"]
del Java_df["HTML"]
del Java_df["CSS"]
del Java_df["Snowflake"]
del Java_df["DataBricks"]
del Java_df["PyTorch"]
del Java_df["GCP"]
del Java_df["Excel"]
del Java_df["VBA"]
del Java_df["PowerBI"]
del Java_df["Tableau"]
del Java_df["Hadoop"]
del Java_df["Scala"]
del Java_df["Java"]
del Java_df["R"]
Java_df

<ipython-input-26-7ac669c611e0>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Java_df["Tools"] = "Java"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
95,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
96,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
107,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,Java
116,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
117,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
128,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,Java
136,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
137,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
148,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,Java
156,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
157,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
168,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,Java
181,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
182,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
193,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,Java
222,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
223,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
234,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,Java
242,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
243,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
254,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,Java
276,IT Specialist,Department of Veterans Affairs,No location provided,66829,Help\r\n \n...,No location provided,NaN,IT Specialist,Java
303,IT Specialist (SYSADMIN),Department of the Army,"Picatinny Arsenal, New Jersey",89537,Help\r\n \n...,Picatinny Arsenal,New Jersey,IT Specialist,Java
305,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
307,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Java
323,IT SPECIALIST (APPSW),Department of Defense,"Indianapolis, Indiana",78136,Help\r\n \n...,Indianapolis,Indiana,IT Specialist,Java
324,IT SPECIALIST (APPSW),Department of Defense,"Indianapolis, Indiana",78136,Help\r\n \n...,Indianapolis,Indiana,IT Specialist,Java
326,IT Specialist (INET),Department of Homeland Security,"Bothell, Washington",84886,Help\r\n \n...,Bothell,Washington,IT Specialist,Java
335,IT SPECIALIST (APPSW),Department of the Navy,"Naval Support Activity, Mechanicsburg, Pennsyl...",78324,Help\r\n \n...,Naval Support Activity,Pennsylvania,IT Specialist,Java
337,IT Specialist (APPSW),Department of the Army,"Key West, Florida",46531,Help\r\n \n...,Key West,Florida,IT Specialist,Java
360,IT Specialist (APPSW),Department of the Treasury,No location provided,92143,Help\r\n \n...,No location provided,NaN,IT Specialist,Java
387,IT SPECIALIST (INFOSEC/APPSW),Department of Defense,"Offutt AFB, Nebraska",77742,Help\r\n \n...,Offutt AFB,Nebraska,IT Specialist,Java
394,IT SPECIALIST (INFOSEC/APPSW),Department of Defense,"Offutt AFB, Nebraska",77742,Help\r\n \n...,Offutt AFB,Nebraska,IT Specialist,Java
435,IT Specialist (Data Management),Department of the Army,"Key West, Florida",98151,Help\r\n \n...,Key West,Florida,IT Specialist,Java
491,IT Specialist (System Administration),Department of Transportation,"Oklahoma City, Oklahoma",78388,Help\r\n \n...,Oklahoma City,Oklahoma,IT Specialist,Java
492,IT Specialist (System Administration),Department of Transportation,"Oklahoma City, Oklahoma",78388,Help\r\n \n...,Oklahoma City,Oklahoma,IT Specialist,Java

In [27]:
df["AI"] = (df["Description"].str.upper()
                            .str.contains(" AI ", regex=False, na=False)
                            .astype(int))
AI_df = df.loc[df["AI"]== 1]
AI_df["Tools"] = "AI"
del AI_df["Python"]
del AI_df["SQL"]
del AI_df["Spark"]
del AI_df["JavaScript"]
del AI_df["NoSQL"]
del AI_df["AWS"]
del AI_df["Azure"]
del AI_df["Google Cloud"]
del AI_df["Cloud"]
del AI_df["HTML"]
del AI_df["CSS"]
del AI_df["Snowflake"]
del AI_df["DataBricks"]
del AI_df["PyTorch"]
del AI_df["GCP"]
del AI_df["Excel"]
del AI_df["VBA"]
del AI_df["PowerBI"]
del AI_df["Tableau"]
del AI_df["Hadoop"]
del AI_df["Scala"]
del AI_df["Java"]
del AI_df["R"]
del AI_df["AI"]

AI_df

<ipython-input-27-f8d6170cf9a0>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AI_df["Tools"] = "AI"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
325,IT SPECIALIST (PLCYPLN),Department of the Navy,"Crane, Indiana",77488,Help\r\n \n...,Crane,Indiana,IT Specialist,AI

In [28]:
df["Machine Learning"] = (df["Description"].str.lower()
                            .str.contains("machine learning", regex=False, na=False)
                            .astype(int))
Machine_Learning_df= df.loc[df["Machine Learning"]== 1]
Machine_Learning_df["Tools"] = "Machine Learning"
del Machine_Learning_df["Python"]
del Machine_Learning_df["SQL"]
del Machine_Learning_df["Spark"]
del Machine_Learning_df["JavaScript"]
del Machine_Learning_df["NoSQL"]
del Machine_Learning_df["AWS"]
del Machine_Learning_df["Azure"]
del Machine_Learning_df["Google Cloud"]
del Machine_Learning_df["Cloud"]
del Machine_Learning_df["HTML"]
del Machine_Learning_df["CSS"]
del Machine_Learning_df["Snowflake"]
del Machine_Learning_df["DataBricks"]
del Machine_Learning_df["PyTorch"]
del Machine_Learning_df["GCP"]
del Machine_Learning_df["Excel"]
del Machine_Learning_df["VBA"]
del Machine_Learning_df["PowerBI"]
del Machine_Learning_df["Tableau"]
del Machine_Learning_df["Hadoop"]
del Machine_Learning_df["Scala"]
del Machine_Learning_df["Java"]
del Machine_Learning_df["Machine Learning"]
del Machine_Learning_df["R"]
del Machine_Learning_df["AI"]
Machine_Learning_df

<ipython-input-28-1baeeabf93c0>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Machine_Learning_df["Tools"] = "Machine Learning"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
325,IT SPECIALIST (PLCYPLN),Department of the Navy,"Crane, Indiana",77488,Help\r\n \n...,Crane,Indiana,IT Specialist,Machine Learning
503,SUPERVISORY IT SPECIALIST (INFOSEC),Department of the Air Force,"Fort Meade, Maryland",12253,Help\r\n \n...,Fort Meade,Maryland,IT Specialist,Machine Learning
552,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
556,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
597,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
601,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
630,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
634,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
663,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
667,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
696,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
700,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
733,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
737,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
766,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
770,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Operations Research Analyst,Machine Learning
802,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
806,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
855,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
859,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
893,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
897,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
931,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
935,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
969,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
973,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
1013,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
1017,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
1051,Operations Research Analyst,Department of Defense,No location provided,92143,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
1055,Operations Research Analyst,Department of the Navy,No location provided,49884,Help\r\n \n...,No location provided,NaN,Research_Analyst,Machine Learning
1074,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1163,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1164,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1165,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1166,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1249,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1337,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1427,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1515,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1523,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1528,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1610,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
1698,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning

In [29]:
df["Deep Learning"] = (df["Description"].str.lower()
                            .str.contains("deep learning", regex=False, na=False)
                            .astype(int))
Deep_Learning_df= df.loc[df["Deep Learning"]== 1]
Deep_Learning_df["Tools"] = "Deep Learning"
del Deep_Learning_df["Python"]
del Deep_Learning_df["SQL"]
del Deep_Learning_df["Spark"]
del Deep_Learning_df["JavaScript"]
del Deep_Learning_df["NoSQL"]
del Deep_Learning_df["AWS"]
del Deep_Learning_df["Azure"]
del Deep_Learning_df["Google Cloud"]
del Deep_Learning_df["Cloud"]
del Deep_Learning_df["HTML"]
del Deep_Learning_df["CSS"]
del Deep_Learning_df["Snowflake"]
del Deep_Learning_df["DataBricks"]
del Deep_Learning_df["PyTorch"]
del Deep_Learning_df["GCP"]
del Deep_Learning_df["Excel"]
del Deep_Learning_df["VBA"]
del Deep_Learning_df["PowerBI"]
del Deep_Learning_df["Tableau"]
del Deep_Learning_df["Hadoop"]
del Deep_Learning_df["Scala"]
del Deep_Learning_df["Java"]
del Deep_Learning_df["Machine Learning"]
del Deep_Learning_df["Deep Learning"]
del Deep_Learning_df["R"]
del Deep_Learning_df["AI"]
Deep_Learning_df

<ipython-input-29-f60f3a4f9ead>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Deep_Learning_df["Tools"] = "Deep Learning"

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
62,Computer Scientist,Department of the Treasury,No location provided,11097,Help\r\n \n...,No location provided,NaN,Computer Scientist,Deep Learning

In [30]:
df["Alteryx"] = (df["Description"].str.lower()
                            .str.contains("Alteryx", regex=False, na=False)
                            .astype(int))
Alteryx_df= df.loc[df["Alteryx"]== 1]
Alteryx_df["Tools"] = "Alteryx"
del Alteryx_df["Python"]
del Alteryx_df["SQL"]
del Alteryx_df["Spark"]
del Alteryx_df["JavaScript"]
del Alteryx_df["NoSQL"]
del Alteryx_df["AWS"]
del Alteryx_df["Azure"]
del Alteryx_df["Google Cloud"]
del Alteryx_df["Cloud"]
del Alteryx_df["HTML"]
del Alteryx_df["CSS"]
del Alteryx_df["Snowflake"]
del Alteryx_df["DataBricks"]
del Alteryx_df["PyTorch"]
del Alteryx_df["GCP"]
del Alteryx_df["Excel"]
del Alteryx_df["VBA"]
del Alteryx_df["PowerBI"]
del Alteryx_df["Tableau"]
del Alteryx_df["Hadoop"]
del Alteryx_df["Scala"]
del Alteryx_df["Java"]
del Alteryx_df["Machine Learning"]
del Alteryx_df["Deep Learning"]
del Alteryx_df["R"]
del Alteryx_df["AI"]
Alteryx_df

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Alteryx, Tools]
Index: []

In [31]:
all_dfs = [Python_df, Sql_df, R_df, NoSql_df, Azure_df,Html_df, css_df, Gcp_df,Excel_df, Vba_df, 
           PowerBI_df, Tableau_df, Hadoop_df, Scala_df, Java_df, AI_df, Machine_Learning_df, 
           Deep_Learning_df]
         
usa_gov_jobs_tools_df = pd.concat(all_dfs).reset_index(drop=True)
usa_gov_jobs_tools_df

,Position Title,Company Name,Company Location,Salary,Description,city,State Name,Job Title,Tools
0,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Python
1,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Python
2,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Python
3,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Python
4,IT Specialist (DATAMGT),Department of the Treasury,"Washington, District of Columbia",11961,Help\r\n \n...,Washington,District of Columbia,IT Specialist,Python
...,...,...,...,...,...,...,...,...,...
825,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
826,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
827,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
828,Supervisory Management and Program Analyst (Da...,Department of Defense,No location provided,12807,Help\r\n \n...,No location provided,NaN,Management program Analyst,Machine Learning
829,Computer Scientist,Department of the Treasury,No location provided,11097,Help\r\n \n...,No location provided,NaN,Computer Scientist,Deep Learning

In [32]:
usa_gov_jobs_tools_df["Tools"].unique().tolist()

['Python',
 'SQL',
 'R',
 'Azure',
 'HTML',
 'CSS',
 'Excel',
 'VBA',
 'PowerBI',
 'Tableau',
 'Hadoop',
 'Scala',
 'Java',
 'AI',
 'Machine Learning',
 'Deep Learning']

In [33]:
usa_gov_jobs_tools_df['Salary'] = usa_gov_jobs_tools_df['Salary'].fillna(0)

In [34]:
usa_gov_jobs_tools_df['Salary']=usa_gov_jobs_tools_df['Salary'].apply(lambda x:round(x,2))
usa_gov_jobs_tools_df["Salary"]= usa_gov_jobs_tools_df["Salary"].astype('int')

In [35]:
usa_gov_jobs_tools_df.dtypes

Position Title      object
Company Name        object
Company Location    object
Salary               int32
Description         object
city                object
State Name          object
Job Title           object
Tools               object
dtype: object

In [36]:
usa_gov_jobs_tools_df.loc[usa_gov_jobs_tools_df['Salary'] == 0]

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [37]:
usa_gov_jobs_tools_df.drop(usa_gov_jobs_tools_df.loc[usa_gov_jobs_tools_df['Salary']==0].index, inplace=True)

In [38]:
usa_gov_jobs_tools_df.loc[usa_gov_jobs_tools_df['Salary'] == 0]

Empty DataFrame
Columns: [Position Title, Company Name, Company Location, Salary, Description, city, State Name, Job Title, Tools]
Index: []

In [39]:
del usa_gov_jobs_tools_df["Description"]

In [40]:
usa_gov_jobs_tools_df["Salary"]= usa_gov_jobs_tools_df["Salary"].apply(str)
usa_gov_jobs_tools_df["Salary"]= '$' + usa_gov_jobs_tools_df["Salary"].astype(str)

In [42]:
# usa_gov_jobs_tools_df.to_csv("../Resources/cpj_usagovjobs_tools_categorized.csv")